const Punctuation = Symbol("punctuation");
const Spelling = Symbol("spelling");
const WordsToCheck = Symbol("wordstocheck");
const Misc = Symbol("misc");

export type IssueId = keyof typeof idlessIssues;
export type Issues = { [key in IssueId]: Issue };
export interface Issue {
  id: IssueId,
  regex: RegExp,
  ui: {
    label: string,
    copy?: string,
    paste?: string,
    checkTypes: any,
  }
}

const idlessIssues = {
  space: { regex: /[ ]{2}/g, ui: { label: "Double spaces", copy: "  ", checkTypes: [Punctuation], }, },
  apostrophe: { regex: /'/g, ui: { label: "'", copy: "\\\'", checkTypes: [Punctuation], }, },
  quote: { regex: /"/g, ui: { label: "\"", copy: "\\\"", checkTypes: [Punctuation], }, },
  too: { regex: /, too\b/ig, ui: { label: ", too", copy: ", too\\b", checkTypes: [Punctuation], }, },
  either: { regex: /, either/ig, ui: { label: ", either", copy: ", either", checkTypes: [Punctuation], }, },
  bang: { regex: /!\?/g, ui: { label: "!? → ?!", copy: "!?", checkTypes: [Punctuation], }, },
  bang2: { regex: /([^!]|^)!!([^!]|$)/g, ui: { label: "!! → ! or !!!", copy: "!!", checkTypes: [Punctuation], }, },
  ellipsis1: { regex: /\.\.\.\./g, ui: { label: "....", copy: "....", checkTypes: [Punctuation], }, },
  ellipsis2: { regex: /\.\.\. [a-z]/g, ui: { label: "... a", copy: "\\.\\.\\. [a-z]", checkTypes: [Punctuation], }, },
  ellipsis3: { regex: /\.\.\.[A-Z]/g, ui: { label: "...A", copy: "\\.\\.\\.[A-Z]", checkTypes: [Punctuation], }, },
  ellipsis4: { regex: /…/g, ui: { label: "… (symbol)", copy: "…", paste: "...", checkTypes: [Punctuation], }, },
  emdash1: { regex: /— /g, ui: { label: "—[space]", copy: "— ", checkTypes: [Punctuation], }, },
  emdash2: { regex: / —/g, ui: { label: "[space]—", copy: " —", checkTypes: [Punctuation], }, },
  causepos: { regex: /‘cause/ig, ui: { label: "‘cause → ’cause", copy: "‘cause", paste: "’cause", checkTypes: [Punctuation], }, },
  suppos: { regex: /‘sup/ig, ui: { label: "‘sup → ’sup", copy: "‘sup", paste: "’sup", checkTypes: [Punctuation], }, },
  empos: { regex: /‘em/ig, ui: { label: "‘em → ’em", copy: "‘em", paste: "’em", checkTypes: [Punctuation], }, },
  startquote: { regex: /”[^“]*?”/g, ui: { label: "Missing start quotes", copy: "”[^“]*?”", checkTypes: [Punctuation], }, },
  endquote: { regex: /“[^”]*?“/g, ui: { label: "Missing end quotes", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },

  absent: { regex: /absent-minded/ig, ui: { label: "absent-minded → absentminded", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  blood: { regex: /blood-red/ig, ui: { label: "blood-red → bloodred", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  bloodsucking: { regex: /blood-sucking/ig, ui: { label: "blood-sucking → bloodsucking", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  crossdress: { regex: /crossdress/ig, ui: { label: "crossdress → cross-dress", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  cross_section: { regex: /cross-section/ig, ui: { label: "cross-section → cross section", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  crystalclear: { regex: /crystal-clear/ig, ui: { label: "crystal-clear → crystal clear", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  deadset: { regex: /dead-set/ig, ui: { label: "dead-set → dead set", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  dealbreaker: { regex: /dealbreaker/ig, ui: { label: "dealbreaker → deal-breaker", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  dutybound: { regex: /duty-bound/ig, ui: { label: "duty-bound → duty bound", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  hand_pick: { regex: /hand-pick/ig, ui: { label: "hand-pick → handpick", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  hardpressed: { regex: /hardpressed/ig, ui: { label: "hardpressed → hard-pressed", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  hard_working: { regex: /hard-working/ig, ui: { label: "hard-working → hardworking", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  iron_fisted: { regex: /iron-fisted/ig, ui: { label: "iron-fisted → ironfisted", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  kind_hearted: { regex: /kind-hearted/ig, ui: { label: "kind-hearted → kindhearted", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  knowhow: { regex: /knowhow/ig, ui: { label: "knowhow → know-how", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  laidback: { regex: /laidback/ig, ui: { label: "laidback → laid-back", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  massproduce: { regex: /mass produce/ig, ui: { label: "mass produce → mass-produce", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  massproduct: { regex: /mass-production/ig, ui: { label: "mass-production → mass production", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  mid_morning: { regex: /mid-morning/i, ui: { label: "mid-morning → midmorning", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  midsentence: { regex: /mid-sentence/ig, ui: { label: "mid-sentence → midsentence", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  offhanded: { regex: /off-handed/ig, ui: { label: "off-handed → offhanded", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  onstage: { regex: /on-stage/ig, ui: { label: "on-stage → onstage", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  re_examine: { regex: /re-examine/ig, ui: { label: "re-examine → reexamine", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  roleplay: { regex: /roleplay/ig, ui: { label: "roleplay → role-play", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  semicircle: { regex: /semi-circle/ig, ui: { label: "semi-circle → semicircle", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  singlehanded: { regex: /singlehanded/ig, ui: { label: "singlehanded → single-handed", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  singleminded: { regex: /singleminded/ig, ui: { label: "singleminded → single-minded", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  slip_up: { regex: /slip-up/ig, ui: { label: "slip-up → slipup", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  tipoff: { regex: /tipoff/ig, ui: { label: "tipoff → tip-off", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },
  vice_versa: { regex: /vice-versa/ig, ui: { label: "vice-versa → vice versa", copy: "“[^”]*?“", checkTypes: [Punctuation], }, },

  alright: { regex: /alright/ig, ui: { label: "alright → all right", copy: "alright", checkTypes: [Punctuation], }, },
  bathhouse: { regex: /bath house/ig, ui: { label: "bath house → bathhouse", copy: "bath house", checkTypes: [Punctuation], }, },
  flipside: { regex: /flipside/ig, ui: { label: "flipside → flip side", copy: "flipside", checkTypes: [Punctuation], }, },
  frontlines: { regex: /frontlines/ig, ui: { label: "frontlines → front lines", copy: "frontlines", checkTypes: [Punctuation], }, },
  goodwill: { regex: /good will/ig, ui: { label: "good will → goodwill", copy: "good will", checkTypes: [Punctuation], }, },
  laugh1: { regex: /haha/ig, ui: { label: "haha → ha ha", copy: "haha", checkTypes: [Punctuation], }, },
  laugh2: { regex: /heehee/ig, ui: { label: "heehee → hee hee", copy: "heehee", checkTypes: [Punctuation], }, },
  keychain: { regex: /keychain/ig, ui: { label: "keychain → key chain", copy: "keychain", checkTypes: [Punctuation], }, },
  lightbulb: { regex: /lightbulb/ig, ui: { label: "lightbulb → light bulb", copy: "lightbulb", checkTypes: [Punctuation], }, },
  nm: { regex: /nevermind/ig, ui: { label: "nevermind → never mind", copy: "nevermind", checkTypes: [Punctuation], }, },
  photoshoot: { regex: /photoshoot/ig, ui: { label: "photoshoot → photo shoot", copy: "photoshoot", checkTypes: [], }, },
  shockwave: { regex: /shockwave/ig, ui: { label: "shockwave → shock wave", copy: "shockwave", checkTypes: [], }, },
  skillset: { regex: /skillset/ig, ui: { label: "skillset → skill set", copy: "skillset", checkTypes: [], }, },
  soul: { regex: /soulmate/ig, ui: { label: "soulmate → soul mate", copy: "soulmate", checkTypes: [], }, },
  tastebud: { regex: /tastebud/ig, ui: { label: "tastebud → taste bud", copy: "tastebud", checkTypes: [], }, },
  timeframe: { regex: /timeframe/ig, ui: { label: "timeframe → time frame", copy: "timeframe", checkTypes: [], }, },
  wishlist: { regex: /wishlist/ig, ui: { label: "wishlist → wish list", copy: "wishlist", checkTypes: [], }, },

  ack: { regex: /acknowledgement/ig, ui: { label: "acknowledgement → acknowledgment", copy: "", checkTypes: [], }, },
  accidently: { regex: /accidently/ig, ui: { label: "accidently → accidentally", copy: "", checkTypes: [], }, },
  ambiance: { regex: /ambiance/ig, ui: { label: "ambiance → ambience", copy: "", checkTypes: [], }, },
  axe: { regex: /\bax\b/ig, ui: { label: "ax → axe", copy: "", checkTypes: [], }, },
  cafe: { regex: /\bcafe\b/ig, ui: { label: "cafe → café", copy: "", checkTypes: [], }, },
  concensus: { regex: /concensus/ig, ui: { label: "concensus → consensus", copy: "", checkTypes: [], }, },
  crystalized: { regex: /crystalized/ig, ui: { label: "crystalized → crystallized", copy: "", checkTypes: [], }, },
  dieing: { regex: /dieing/ig, ui: { label: "dieing → dying", copy: "", checkTypes: [], }, },
  forsaw: { regex: /forsaw/ig, ui: { label: "forsaw → foresaw", copy: "", checkTypes: [], }, },
  forsee: { regex: /forsee/ig, ui: { label: "forsee → foresee", copy: "", checkTypes: [], }, },
  geez: { regex: /\bgeez\b/ig, ui: { label: "geez → jeez", copy: "", checkTypes: [], }, },
  grevious: { regex: /grevious/ig, ui: { label: "grevious → grievous", copy: "", checkTypes: [], }, },
  grinded: { regex: /grinded/ig, ui: { label: "grinded → ground", copy: "", checkTypes: [], }, },
  guerrila: { regex: /guerrila/ig, ui: { label: "guerrila → guerrilla", copy: "", checkTypes: [], }, },
  guerilla: { regex: /guerilla/ig, ui: { label: "guerilla → guerrilla", copy: "", checkTypes: [], }, },
  judge: { regex: /judgement/ig, ui: { label: "judgement → judgment", copy: "", checkTypes: [], }, },
  mischevious: { regex: /mischevious/ig, ui: { label: "mischevious → mischievous", copy: "", checkTypes: [], }, },
  ocher: { regex: /ochre/ig, ui: { label: "ochre → ocher", copy: "", checkTypes: [], }, },
  omelette: { regex: /omelette/ig, ui: { label: "omelette → omelet", copy: "", checkTypes: [], }, },
  publically: { regex: /publically/ig, ui: { label: "publically → publicly", copy: "", checkTypes: [], }, },
  strait: { regex: /straightlaced/ig, ui: { label: "straightlaced → straitlaced", copy: "", checkTypes: [], }, },
  underaged: { regex: /underaged/ig, ui: { label: "underaged → underage", copy: "", checkTypes: [], }, },
  kempt: { regex: /well-kempt/ig, ui: { label: "well-kempt → well-kept", copy: "", checkTypes: [], }, },
  woah: { regex: /woah/ig, ui: { label: "woah → whoa", copy: "", checkTypes: [], }, },
  worshiping: { regex: /worshiping/ig, ui: { label: "worshiping → worshipping", copy: "", checkTypes: [], }, },
  worshiper: { regex: /worshiper/ig, ui: { label: "worshiper → worshipper", copy: "", checkTypes: [], }, },

  aircon: { regex: /aircon/ig, ui: { label: "aircon → AC or air conditioning", copy: "", checkTypes: [], }, },
  apologise: { regex: /apologise/ig, ui: { label: "apologise → apologize", copy: "", checkTypes: [], }, },
  cancelled: { regex: /cancelled/ig, ui: { label: "cancelled → canceled", copy: "", checkTypes: [], }, },
  cancelling: { regex: /cancelling/ig, ui: { label: "cancelling → canceling", copy: "", checkTypes: [], }, },
  cancelation: { regex: /cancelation/ig, ui: { label: "cancelation → cancellation", copy: "", checkTypes: [], }, },
  colour: { regex: /colour/ig, ui: { label: "colour → color", copy: "", checkTypes: [], }, },
  centre: { regex: /centre/ig, ui: { label: "centre → center", copy: "", checkTypes: [], }, },
  defence: { regex: /defence/ig, ui: { label: "defence → defense", copy: "", checkTypes: [], }, },
  emphasise: { regex: /emphasise/ig, ui: { label: "emphasise → emphasize", copy: "", checkTypes: [], }, },
  grey: { regex: /grey/ig, ui: { label: "grey → gray", copy: "", checkTypes: [], }, },
  meagre: { regex: /meagre/ig, ui: { label: "meagre → meager", copy: "", checkTypes: [], }, },
  miniscule: { regex: /miniscule/ig, ui: { label: "miniscule → minuscule", copy: "", checkTypes: [], }, },
  moustache: { regex: /moustache/ig, ui: { label: "moustache → mustache", copy: "", checkTypes: [], }, },
  offence: { regex: /offence/ig, ui: { label: "offence → offense", copy: "", checkTypes: [], }, },
  plough: { regex: /plough/ig, ui: { label: "plough → plow", copy: "", checkTypes: [], }, },
  signalling: { regex: /signalling/ig, ui: { label: "signalling → signaling", copy: "", checkTypes: [], }, },
  sizeable: { regex: /sizeable/ig, ui: { label: "sizeable → sizable", copy: "", checkTypes: [], }, },
  smoulder: { regex: /smoulder/ig, ui: { label: "smoulder → smolder", copy: "", checkTypes: [], }, },
  travelling: { regex: /travelling/ig, ui: { label: "travelling → traveling", copy: "", checkTypes: [], }, },
  traveller: { regex: /traveller/ig, ui: { label: "traveller → traveler", copy: "", checkTypes: [], }, },

  frontline1: { regex: /frontline/ig, ui: { label: "frontline (adjective)", copy: "", checkTypes: [], }, },
  frontline2: { regex: /front line/ig, ui: { label: "front line (noun)", copy: "", checkTypes: [], }, },
  grit: { regex: /\bgritb/ig, ui: { label: "grit (should be gritted, past tense?)", copy: "", checkTypes: [], }, },
  heroin: { regex: /heroin[^e]/ig, ui: { label: "heroin (heroine?)", copy: "", checkTypes: [], }, },
  lead: { regex: /\blead\b/ig, ui: { label: "lead (should be led, past tense?)", copy: "", checkTypes: [], }, },
  principal: { regex: /principal/ig, ui: { label: "principal (head of a school)", copy: "", checkTypes: [], }, },
  principle: { regex: /principle/ig, ui: { label: "principle (concept)", copy: "", checkTypes: [], }, },
  psych: { regex: /psych[^e]\b/ig, ui: { label: "psych (verb)", copy: "", checkTypes: [], }, },
  psyche: { regex: /\bpsyche/ig, ui: { label: "psyche (noun)", copy: "", checkTypes: [], }, },
  pubic: { regex: /pubic/ig, ui: { label: "pubic (public?)", copy: "", checkTypes: [], }, },
  sheath: { regex: /sheath[^e]/ig, ui: { label: "sheath (noun)", copy: "", checkTypes: [], }, },
  sheathe: { regex: /sheathe/ig, ui: { label: "sheathe (verb)", copy: "", checkTypes: [], }, },
  first_hand: { regex: /first-hand/ig, ui: { label: "first-hand → firsthand", copy: "", checkTypes: [], }, },
  mid_twenties: { regex: /mid-twenties/ig, ui: { label: "mid-twenties → midtwenties", copy: "", checkTypes: [], }, },
  mid_thirties: { regex: /mid-thirties/ig, ui: { label: "mid-thirties → midthirties", copy: "", checkTypes: [], }, },
  mid_forties: { regex: /mid-forties/ig, ui: { label: "mid-forties → midforties", copy: "", checkTypes: [], }, },
  onetime: { regex: /one-time/ig, ui: { label: "one-time → onetime", copy: "", checkTypes: [], }, },
  second_hand: { regex: /second-hand/ig, ui: { label: "second-hand → secondhand", copy: "", checkTypes: [], }, },
  twentyfourseven: { regex: /twenty-four-seven/ig, ui: { label: "twenty-four-seven → twenty-four seven", copy: "", checkTypes: [], }, },

  coup: { regex: /coup d’etat/ig, ui: { label: "coup d’etat →  coup d’état", copy: "", checkTypes: [], }, },
  dejavu: { regex: /deja vu/ig, ui: { label: "deja vu → déjà vu", copy: "", checkTypes: [], }, },
  gatling: { regex: /gatling gun/g, ui: { label: "gatling gun → Gatling gun", copy: "", checkTypes: [], }, },
  fiance: { regex: /\bfiance[^e]/ig, ui: { label: "fiance → fiancé", copy: "", checkTypes: [], }, },
  fiancee: { regex: /fiancee/ig, ui: { label: "fiancee → fiancée", copy: "", checkTypes: [], }, },
  mache: { regex: /paper mache/ig, ui: { label: "paper mache → paper-mache or papier mâché", copy: "", checkTypes: [], }, },
  swiss: { regex: /swiss cheese/g, ui: { label: "swiss cheese → Swiss cheese", copy: "", checkTypes: [], }, },
  tete_a_tete: { regex: /tete-a-tete/ig, ui: { label: "tete-a-tete → tête-à-tête", copy: "", checkTypes: [], }, },
  adverb: { regex: /ly-/ig, ui: { label: "hyphenated averbs (ly-)", copy: "", checkTypes: [], }, },
  toward: { regex: /towards/ig, ui: { label: "towards", copy: "", checkTypes: [], }, },
  towards: { regex: /toward($|[^s])/ig, ui: { label: "toward", copy: "", checkTypes: [], }, },
  afterward: { regex: /afterwards/ig, ui: { label: "afterwards", copy: "", checkTypes: [], }, },
  afterwards: { regex: /afterward($|[^s])/ig, ui: { label: "afterward", copy: "", checkTypes: [], }, },
};

const unusedTypeCheck = idlessIssues as { [key: string]: Omit<Issue, "id"> };

type IdlessIssues = { [key in IssueId]: Omit<Issues[key], 'id'> };

function copyObjectIdsToValues(idlessIssues: IdlessIssues): Issues {
  const issues: Partial<Issues> = {};
  for (const key in idlessIssues) {
    const id = key as IssueId;
    issues[id] = { id, ...idlessIssues[id] as Omit<Issue, 'id'> };
  }
  return issues as Issues;
}

export const issues = copyObjectIdsToValues(idlessIssues);
