export type IssueId = keyof typeof idlessIssues;
export type Issues = { [key in IssueId]: Issue };

export const IssueType = {
  PG: Symbol("punctuationAndGrammar"),
  SP: Symbol("spelling"),
  SW: Symbol("similarWords"),
  SL: Symbol("slurs"),
}

export interface Issue {
  id: IssueId,
  regex: RegExp,
  ui: {
    label: string,
    toLabel?: string,
    copy?: string,
    paste?: string,
    copyLabels?: boolean,
    mw?: string,
  }
  type: Symbol,
}

const idlessIssues = {

  // PUNCTUATION & GRAMMAR
  space: { regex: /[ ]{2}/g, ui: { label: "Two spaces", toLabel: "One space", copy: "  ", paste: " " }, type: IssueType.PG },
  space2: { regex: /\n /g, ui: { label: "Space after newline", copy: "\\n " }, type: IssueType.PG },
  space3: { regex: / \.([^\.]|$)/g, ui: { label: "Space before period", copy: " \\.([^\\.]|$)" }, type: IssueType.PG }, 
  period: { regex: /([^\.]|^)\.\.([^\.]|$)/g, ui: { label: "..", toLabel: ". or ...", copy: "([^\\.]|^)\\.\\.([^\\.]|$)" }, type: IssueType.PG },
  period2: { regex: /(^|[^\.])\.[?!$]/g, ui: { label: ". before ? or !", copy: "[^\\.]\\.[?!$]" }, type: IssueType.PG },
  period3: { regex: /[?!]\./g, ui: { label: ". after ? or !", copy: "[?!]\\." }, type: IssueType.PG },
  period4: { regex: /”\.([^\.])/ig, ui: { label: "Period outside ”", copy: "”\\.([^\\.])" }, type: IssueType.PG },
  period5: { regex: /’\.([^\.])/ig, ui: { label: "Period outside ’", copy: "’\\.([^\\.])" }, type: IssueType.PG },
  apostrophe: { regex: /'/g, ui: { label: "Straight '", copy: "\\\'" }, type: IssueType.PG },
  quote: { regex: /"/g, ui: { label: "Straight \"", copy: "\\\"" }, type: IssueType.PG },
  startquote: { regex: /”[^“]*?”/g, ui: { label: "Missing start quotes", copy: "”[^“]*?”" }, type: IssueType.PG },
  endquote: { regex: /“[^”]*?“/g, ui: { label: "Missing end quotes", copy: "“[^”]*?“" }, type: IssueType.PG },
  apostrophe2: { regex: /‘s\b/ig, ui: { label: "‘s", toLabel: "’s", copy: "‘s\\b", paste: "’s" }, type: IssueType.PG },
  possessive: { regex: /s’\s/ig, ui: { label: "s’ (singular possessive?)", toLabel: "s’s", copy: "s’\\s", paste: "s’s" }, type: IssueType.PG },
  comma: { regex: /”,/ig, ui: { label: "Comma outside ”", copy: "”," }, type: IssueType.PG },
  comma2: { regex: /’,/ig, ui: { label: "Comma outside ’", copy: "’," }, type: IssueType.PG },
  too: { regex: /, too\b/ig, ui: { label: ", too", copy: ", too\\b" }, type: IssueType.PG },
  either: { regex: /, either/ig, ui: { label: ", either", copy: ", either" }, type: IssueType.PG },
  bang: { regex: /!\?/g, ui: { label: "!?", toLabel: "?!", copy: "!\\?", paste: "\\?!" }, type: IssueType.PG },
  bang2: { regex: /([^!]|^)!!([^!]|$)/g, ui: { label: "!!", toLabel: "! or !!!", copy: "([^!]|^)!!([^!]|$)" }, type: IssueType.PG },
  ellipsis1: { regex: /\.\.\.\./g, ui: { label: "....", copy: "\\.\\.\\.\\." }, type: IssueType.PG },
  ellipsis2: { regex: /\.\.\. [a-z]/g, ui: { label: "... a", copy: "\\.\\.\\. [a-z]" }, type: IssueType.PG },
  ellipsis3: { regex: /\.\.\.[A-Z]/g, ui: { label: "...A", copy: "\\.\\.\\.[A-Z]" }, type: IssueType.PG },
  ellipsis4: { regex: /…/g, ui: { label: "… (symbol)", toLabel: "...", copy: "[\\u2026]", paste: "..." }, type: IssueType.PG },
  emdash1: { regex: /— /g, ui: { label: "—[space]", copy: "— " }, type: IssueType.PG },
  emdash2: { regex: / —/g, ui: { label: "[space]—", copy: " —" }, type: IssueType.PG },
  endash: { regex: /–/g, ui: { label: "– (endash)", copy: "–" }, type: IssueType.PG },
  double_hyphen: { regex: /--/g, ui: { label: "-- (double hyphen)", copy: "--" }, type: IssueType.PG },
  t_th: { regex: /t-th/ig, ui: { label: "t-th", toLabel: "th-th (stutter?)", copy: "t-th" }, type: IssueType.PG },
  w_wh: { regex: /w-wh/ig, ui: { label: "w-wh", toLabel: "wh-wh (stutter?)", copy: "w-wh" }, type: IssueType.PG },
  adverb: { regex: /ly-(?!(?:fledged))/ig, ui: { label: "hyphenated adverbs (ly-)", copy: "ly-(?!(?:fledged))" }, type: IssueType.PG },
  hyphen_numbers: { regex: /(twen|thir|for|fif|six|seven|eigh|nine)ty (one|two|three|four|five|six|seven|eight|nine)/ig, ui: { label: "Hyphenate numbers [21-99]", copy: "(twen|thir|for|fif|six|seven|eigh|nine)ty (one|two|three|four|five|six|seven|eight|nine)" }, type: IssueType.PG },
  double_possessive: { regex: /.+’s and .+’s/ig, ui: { label: "Double possessive?", copy: "'s \\band ([^\\s]+)'s" }, type: IssueType.PG },
  less_plural: { regex: /\bless [a-z]+(?<!ou)s\b/ig, ui: { label: "'Less' used for countable quantity?", copy: "\\bless [a-z]+(?<!ou)s\\b" }, type: IssueType.PG },
  causepos: { regex: /‘cause\b/ig, ui: { label: "‘cause", toLabel: "’cause", copy: "‘cause\\b", paste: "’cause" }, type: IssueType.PG },
  suppos: { regex: /‘sup\b/ig, ui: { label: "‘sup", toLabel: "’sup", copy: "‘sup\\b", paste: "’sup" }, type: IssueType.PG },
  empos: { regex: /‘em\b/ig, ui: { label: "‘em", toLabel: "’em", copy: "‘em\\b", paste: "’em" }, type: IssueType.PG },
  boutpos: { regex: /‘bout\b/ig, ui: { label: "‘bout", toLabel: "’bout", copy: "‘bout\\b", paste: "’bout" }, type: IssueType.PG },
  notherpos: { regex: /‘nother\b/ig, ui: { label: "‘nother", toLabel: "’nother", copy: "‘nother\\b", paste: "’nother" }, type: IssueType.PG },
  forepos: { regex: /‘fore\b/ig, ui: { label: "‘fore", toLabel: "’fore", copy: "‘fore\\b", paste: "’fore" }, type: IssueType.PG },
  fraidpos: { regex: /‘fraid\b/ig, ui: { label: "‘fraid", toLabel: "’fraid", copy: "‘fraid\\b", paste: "’fraid" }, type: IssueType.PG },
  neathpos: { regex: /‘neath\b/ig, ui: { label: "‘neath", toLabel: "’neath", copy: "‘neath\\b", paste: "’neath" }, type: IssueType.PG },
  gainstpos: { regex: /‘gainst\b/ig, ui: { label: "‘gainst", toLabel: "’gainst", copy: "‘gainst\\b", paste: "’gainst" }, type: IssueType.PG },
  ceptpos: { regex: /‘cept\b/ig, ui: { label: "‘cept", toLabel: "’cept", copy: "‘cept\\b", paste: "’cept" }, type: IssueType.PG },
  roundpos: { regex: /‘round\b/ig, ui: { label: "‘round", toLabel: "’round", copy: "‘round\\b", paste: "’round" }, type: IssueType.PG },
  tilpos: { regex: /‘til\b/ig, ui: { label: "‘til", toLabel: "’til", copy: "‘til\\b", paste: "’til" }, type: IssueType.PG },
  tispos: { regex: /‘tis\b/ig, ui: { label: "‘tis", toLabel: "’tis", copy: "‘tis\\b", paste: "’tis" }, type: IssueType.PG },
  twaspos: { regex: /‘twas\b/ig, ui: { label: "‘twas", toLabel: "’twas", copy: "‘twas\\b", paste: "’twas" }, type: IssueType.PG },
  tweenpos: { regex: /‘tween\b/ig, ui: { label: "‘tween", toLabel: "’tween", copy: "‘tween\\b", paste: "’tween" }, type: IssueType.PG },
  twerepos: { regex: /‘twere\b/ig, ui: { label: "‘twere", toLabel: "’twere", copy: "‘twere\\b", paste: "’twere" }, type: IssueType.PG },
  twixtpos: { regex: /‘twixt\b/ig, ui: { label: "‘twixt", toLabel: "’twixt", copy: "‘twixt\\b", paste: "’twixt" }, type: IssueType.PG },
  space_before_measurement: { regex: /[0-9](cm|m|km|centimeter|centimeters|meter|meters|kilometer|kilometers|g|kg|gram|grams|kilogram|kilograms)\b/ig, ui: { label: "No space before measurement", toLabel: "Add space before measurement", copy: "[0-9](cm|m|km|centimeter|centimeters|meter|meters|kilometer|kilometers|g|kg|gram|grams|kilogram|kilograms)\\b" }, type: IssueType.PG },

  // A through E
  absent_minded: { regex: /absent-minded/ig, ui: { label: "absent-minded", toLabel: "absentminded", copyLabels: true, mw: "absentminded" }, type: IssueType.SP },
  accidently: { regex: /accidently/ig, ui: { label: "accidently", toLabel: "accidentally", copyLabels: true }, type: IssueType.SP },
  ack: { regex: /acknowledgement/ig, ui: { label: "acknowledgement", toLabel: "acknowledgment", copyLabels: true, mw: "acknowledgment" }, type: IssueType.SP },
  adult_like: { regex: /adult-like/ig, ui: { label: "adult-like", toLabel: "adultlike",  copyLabels: true, mw: "adultlike" }, type: IssueType.SP },
  after_effect: { regex: /after-effect/ig, ui: { label: "after-effect", toLabel: "aftereffect", copyLabels: true, mw: "aftereffect" }, type: IssueType.SP },
  ahaha: { regex: /ahaha/ig, ui: { label: "ahaha", toLabel: "ah ha ha", copyLabels: true }, type: IssueType.SP },
  aircon: { regex: /aircon/ig, ui: { label: "aircon", toLabel: "AC or air conditioning", copy: "aircon" }, type: IssueType.SP },
  air_tight: { regex: /air-tight/ig, ui: { label: "air-tight", toLabel: "airtight", copyLabels: true, mw: "airtight" }, type: IssueType.SP },
  all_out: { regex: /all out/ig, ui: { label: "all out (adverb)", copy: "all out", mw: "all out" }, type: IssueType.SP },
  all_out2: { regex: /all-out/ig, ui: { label: "all-out (adjective)", copy: "all-out", mw: "all-out" }, type: IssueType.SP },
  alright: { regex: /alright/ig, ui: { label: "alright", toLabel: "all right", copyLabels: true, mw: "all right" }, type: IssueType.SP },
  ambiance: { regex: /ambiance/ig, ui: { label: "ambiance", toLabel: "ambience",  copyLabels: true, mw: "ambience" }, type: IssueType.SP },
  ambiant: { regex: /ambiant/ig, ui: { label: "ambiant", toLabel: "ambient",  copyLabels: true, mw: "ambient" }, type: IssueType.SP },
  animal_like: { regex: /animal-like/ig, ui: { label: "animal-like", toLabel: "animallike",  copyLabels: true, mw: "animallike" }, type: IssueType.SP },
  arm_in_arm: { regex: /arm-in-arm/ig, ui: { label: "arm-in-arm", toLabel: "arm in arm",  copyLabels: true, mw: "arm in arm" }, type: IssueType.SP },
  apologise: { regex: /apologise/ig, ui: { label: "apologise", toLabel: "apologize",  copyLabels: true, mw: "apologize" }, type: IssueType.SP },
  apologising: { regex: /apologising/ig, ui: { label: "apologising", toLabel: "apologizing",  copyLabels: true }, type: IssueType.SP },
  auto_pilot: { regex: /auto-pilot/ig, ui: { label: "auto-pilot", toLabel: "autopilot", copyLabels: true, mw: "autopilot" }, type: IssueType.SP },
  axe: { regex: /\bax\b/ig, ui: { label: "ax", toLabel: "axe", copy: "\\bax\\b", paste: "axe" }, type: IssueType.SP },
  badmouth: { regex: /badmouth/ig, ui: { label: "badmouth", toLabel: "bad-mouth", copyLabels: true, mw: "bad-mouth" }, type: IssueType.SP },
  bad_mouth: { regex: /bad mouth/ig, ui: { label: "bad mouth", toLabel: "bad-mouth (verb?)", copy: "bad mouth", paste: "bad-mouth", mw: "bad-mouth" }, type: IssueType.SP },
  back_and_forth: { regex: /back-and-forth/ig, ui: { label: "back-and-forth (noun)", copy: "back-and-forth", mw: "back-and-forth" }, type: IssueType.SP },
  back_and_forth2: { regex: /back and forth/ig, ui: { label: "back and forth (adverb)", copy: "back and forth", mw: "back and forth" }, type: IssueType.SP },
  back_to_back: { regex: /back to back/ig, ui: { label: "back to back", toLabel: "back-to-back",  copyLabels: true, mw: "back-to-back" }, type: IssueType.SP },
  backup: { regex: /backup/ig, ui: { label: "backup (noun)", copy: "backup", mw: "backup" }, type: IssueType.SP },
  back_up: { regex: /\bback up\b/ig, ui: { label: "back up (verb)", copy: "\\bback up\\b", mw: "back up" }, type: IssueType.SP },
  back_up2: { regex: /back-up/ig, ui: { label: "back-up", toLabel: "backup (noun) or back up (verb)", copy: "backup", mw: "back up" }, type: IssueType.SP },
  barebones: { regex: /barebones/ig, ui: { label: "barebones", toLabel: "bare-bones",  copyLabels: true, mw: "bare-bones" }, type: IssueType.SP },
  bare_bones: { regex: /bare bones/ig, ui: { label: "bare bones", toLabel: "bare-bones",  copyLabels: true, mw: "bare-bones" }, type: IssueType.SP },
  bathhouse: { regex: /bath house/ig, ui: { label: "bath house", toLabel: "bathhouse",  copyLabels: true, mw: "bathhouse" }, type: IssueType.SP },
  bed_time: { regex: /bed time/ig, ui: { label: "bed time", toLabel: "bedtime",  copyLabels: true, mw: "bedtime" }, type: IssueType.SP },
  best_seller: { regex: /best-seller/ig, ui: { label: "best-seller", toLabel: "bestseller",  copyLabels: true, mw: "bestseller" }, type: IssueType.SP },
  bite_sized: { regex: /bite-sized/ig, ui: { label: "bite-sized", toLabel: "bite-size", copyLabels: true, mw: "bite-size" }, type: IssueType.SP },
  black_and_white: { regex: /black and white/ig, ui: { label: "black and white", toLabel: "black-and-white", copyLabels: true, mw: "black-and-white" }, type: IssueType.SP },
  blindspot: { regex: /blindspot/ig, ui: { label: "blindspot", toLabel: "blind spot",  copyLabels: true, mw: "blind spot" }, type: IssueType.SP },
  blood_curdling: { regex: /blood-curdling/ig, ui: { label: "blood-curdling", toLabel: "bloodcurdling",  copyLabels: true, mw: "bloodcurdling" }, type: IssueType.SP },
  blood_curdling2: { regex: /blood curdling/ig, ui: { label: "blood curdling", toLabel: "bloodcurdling",  copyLabels: true, mw: "bloodcurdling" }, type: IssueType.SP },
  blood_red: { regex: /blood-red/ig, ui: { label: "blood-red", toLabel: "bloodred", copyLabels: true, mw: "bloodred" }, type: IssueType.SP },
  blood_red2: { regex: /blood red/ig, ui: { label: "blood red", toLabel: "bloodred", copyLabels: true, mw: "bloodred" }, type: IssueType.SP },
  blood_stain: { regex: /blood stain/ig, ui: { label: "blood stain", toLabel: "bloodstain", copyLabels: true, mw: "bloodstain" }, type: IssueType.SP },
  blood_stain2: { regex: /blood-stain/ig, ui: { label: "blood-stain", toLabel: "bloodstain", copyLabels: true, mw: "bloodstain" }, type: IssueType.SP },
  blood_sucker: { regex: /blood-sucker/ig, ui: { label: "blood-sucker", toLabel: "bloodsucker", copyLabels: true, mw: "bloodsucker" }, type: IssueType.SP },
  blood_sucking: { regex: /blood-sucking/ig, ui: { label: "blood-sucking", toLabel: "bloodsucking", copyLabels: true, mw: "bloodsucking" }, type: IssueType.SP },
  braindead: { regex: /braindead/ig, ui: { label: "braindead", toLabel: "brain-dead", copyLabels: true, mw: "brain-dead" }, type: IssueType.SP },
  brain_dead: { regex: /brain dead/ig, ui: { label: "brain dead", toLabel: "brain-dead", copyLabels: true, mw: "brain-dead" }, type: IssueType.SP },
  broadminded: { regex: /broadminded/ig, ui: { label: "broadminded", toLabel: "broad-minded", copyLabels: true, mw: "broad-minded" }, type: IssueType.SP },
  build_up: { regex: /build-up/ig, ui: { label: "build-up", toLabel: "buildup", copyLabels: true, mw: "buildup" }, type: IssueType.SP },
  bullseye: { regex: /bullseye/ig, ui: { label: "bullseye", toLabel: "bull’s-eye", copyLabels: true, mw: "bull's-eye" }, type: IssueType.SP },
  bulls_eye: { regex: /bull’s eye/ig, ui: { label: "bull’s eye", toLabel: "bull’s-eye", copyLabels: true, mw: "bull's-eye" }, type: IssueType.SP },
  bye_bye: { regex: /bye bye/ig, ui: { label: "bye bye", toLabel: "bye-bye", copyLabels: true, mw: "bye-bye" }, type: IssueType.SP },
  cafe: { regex: /\bcafe\b/ig, ui: { label: "cafe", toLabel: "café", copyLabels: true, mw: "café" }, type: IssueType.SP },
  cancelled: { regex: /cancelled/ig, ui: { label: "cancelled", toLabel: "canceled", copyLabels: true, mw: "cancel" }, type: IssueType.SP },
  cancelling: { regex: /cancelling/ig, ui: { label: "cancelling", toLabel: "canceling", copyLabels: true, mw: "canceling" }, type: IssueType.SP },
  cancelation: { regex: /cancelation/ig, ui: { label: "cancelation", toLabel: "cancellation", copyLabels: true, mw: "cancellation" }, type: IssueType.SP },
  candle_holder: { regex: /candle holder/ig, ui: { label: "candle holder", toLabel: "candleholder", copyLabels: true, mw: "candleholder" }, type: IssueType.SP },
  catch_phrase: { regex: /catch phrase/ig, ui: { label: "catch phrase", toLabel: "catchphrase", copyLabels: true, mw: "catchphrase" }, type: IssueType.SP },
  catch_phrase2: { regex: /catch-phrase/ig, ui: { label: "catch-phrase", toLabel: "catchphrase", copyLabels: true, mw: "catchphrase" }, type: IssueType.SP },
  centre: { regex: /centre/ig, ui: { label: "centre", toLabel: "center", copyLabels: true, mw: "center" }, type: IssueType.SP },
  chainmail: { regex: /chainmail/ig, ui: { label: "chainmail", toLabel: "chain mail", copyLabels: true, mw: "chain mail" }, type: IssueType.SP },
  chit_chat: { regex: /chit-chat/ig, ui: { label: "chit-chat", toLabel: "chitchat", copyLabels: true, mw: "chitchat" }, type: IssueType.SP },
  chit_chat2: { regex: /chit chat/ig, ui: { label: "chit chat", toLabel: "chitchat", copyLabels: true, mw: "chitchat" }, type: IssueType.SP },
  chokehold: { regex: /chokehold/ig, ui: { label: "chokehold", toLabel: "choke hold", copyLabels: true, mw: "choke hold" }, type: IssueType.SP },
  city_state: { regex: /city state/ig, ui: { label: "city state", toLabel: "city-state (noun?)", copy: "city state", paste: "city-state", mw: "city-state" }, type: IssueType.SP },
  clean_up: { regex: /clean-up/ig, ui: { label: "clean-up", toLabel: "cleanup", copyLabels: true, mw: "cleanup" }, type: IssueType.SP },
  clear_headed: { regex: /clear-headed/ig, ui: { label: "clear-headed", toLabel: "clearheaded", copyLabels: true, mw: "clearheaded" }, type: IssueType.SP },
  cliche: { regex: /cliche/ig, ui: { label: "cliche", toLabel: "cliché", copyLabels: true, mw: "cliché" }, type: IssueType.SP },
  cliff_hanger: { regex: /cliff hanger/ig, ui: { label: "cliff hanger", toLabel: "cliff-hanger", copyLabels: true, mw: "cliff-hanger" }, type: IssueType.SP },
  cliffhanger: { regex: /cliffhanger/ig, ui: { label: "cliffhanger", toLabel: "cliff-hanger", copyLabels: true, mw: "cliff-hanger" }, type: IssueType.SP },
  co_worker: { regex: /co-worker/ig, ui: { label: "co-worker", toLabel: "coworker", copyLabels: true, mw: "coworker" }, type: IssueType.SP },
  cold_hearted: { regex: /cold-hearted/ig, ui: { label: "cold-hearted", toLabel: "coldhearted", copyLabels: true, mw: "coldhearted" }, type: IssueType.SP },
  collar_bone: { regex: /collar bone/ig, ui: { label: "collar bone", toLabel: "collarbone", copyLabels: true, mw: "collarbone" }, type: IssueType.SP },
  colour: { regex: /colour/ig, ui: { label: "colour", toLabel: "color", copyLabels: true, mw: "color" }, type: IssueType.SP },
  concensus: { regex: /concensus/ig, ui: { label: "concensus", toLabel: "consensus", copyLabels: true, mw: "consensus" }, type: IssueType.SP },
  counter_attack: { regex: /counter attack/ig, ui: { label: "counter attack", toLabel: "counterattack", copyLabels: true, mw: "counterattack" }, type: IssueType.SP },
  coup: { regex: /coup d’etat/ig, ui: { label: "coup d’etat", toLabel: "coup d’état", copyLabels: true, mw: "coup d’état" }, type: IssueType.SP },
  coup_de_grace: { regex: /coup de grace/ig, ui: { label: "coup de grace", toLabel: "coup de grâce", copyLabels: true, mw: "coup de grâce" }, type: IssueType.SP },
  criss_cross: { regex: /criss-cross/ig, ui: { label: "criss-cross", toLabel: "crisscross", copyLabels: true, mw: "crisscross" }, type: IssueType.SP },
  crossdress: { regex: /crossdress/ig, ui: { label: "crossdress", toLabel: "cross-dress", copyLabels: true, mw: "crossdress" }, type: IssueType.SP },
  cross_fire: { regex: /cross-fire/ig, ui: { label: "cross-fire", toLabel: "cross fire", copyLabels: true, mw: "cross fire" }, type: IssueType.SP },
  crossfire: { regex: /crossfire/ig, ui: { label: "crossfire", toLabel: "cross fire", copyLabels: true, mw: "cross fire" }, type: IssueType.SP },
  cross_hair: { regex: /cross-hair/ig, ui: { label: "cross-hair", toLabel: "crosshair", copyLabels: true, mw: "crosshair" }, type: IssueType.SP },
  cross_hair2: { regex: /cross hair/ig, ui: { label: "cross hair", toLabel: "crosshair", copyLabels: true, mw: "crosshair" }, type: IssueType.SP },
  cross_section: { regex: /cross-section/ig, ui: { label: "cross-section", toLabel: "cross section", copyLabels: true, mw: "cross section" }, type: IssueType.SP },
  crystal_clear: { regex: /crystal-clear/ig, ui: { label: "crystal-clear", toLabel: "crystal clear", copyLabels: true, mw: "crystal clear" }, type: IssueType.SP },
  crystalized: { regex: /crystalized/ig, ui: { label: "crystalized", toLabel: "crystallized", copyLabels: true, mw: "crystallize" }, type: IssueType.SP },
  cut_and_dried: { regex: /cut and dried/ig, ui: { label: "cut and dried", toLabel: "cut-and-dried", copyLabels: true, mw: "cut-and-dried" }, type: IssueType.SP },
  cut_and_dry: { regex: /cut and dry/ig, ui: { label: "cut and dry", toLabel: "cut-and-dried", copyLabels: true, mw: "cut-and-dried" }, type: IssueType.SP },
  cut_and_dry2: { regex: /cut-and-dry/ig, ui: { label: "cut-and-dry", toLabel: "cut-and-dried", copyLabels: true, mw: "cut-and-dried" }, type: IssueType.SP }, 
  damndest: { regex: /damndest/ig, ui: { label: "damndest", toLabel: "damnedest", copyLabels: true, mw: "damnedest" }, type: IssueType.SP },
  day_long: { regex: /day-long/ig, ui: { label: "day-long", toLabel: "daylong", copyLabels: true, mw: "daylong" }, type: IssueType.SP },
  day_to_day_life: { regex: /day to day life/ig, ui: { label: "day to day life", toLabel: "day-to-day life", copyLabels: true, mw: "day-to-day" }, type: IssueType.SP },
  deadset: { regex: /deadset/ig, ui: { label: "deadset", toLabel: "dead set", copyLabels: true, mw: "dead set" }, type: IssueType.SP },
  dead_set: { regex: /dead-set/ig, ui: { label: "dead-set", toLabel: "dead set", copyLabels: true, mw: "dead set" }, type: IssueType.SP },
  deal_breaker: { regex: /deal breaker/ig, ui: { label: "deal breaker", toLabel: "deal-breaker", copyLabels: true }, type: IssueType.SP },
  dealbreaker: { regex: /dealbreaker/ig, ui: { label: "dealbreaker", toLabel: "deal-breaker", copyLabels: true }, type: IssueType.SP },
  deal_maker: { regex: /deal-maker/ig, ui: { label: "deal-maker", toLabel: "dealmaker", copyLabels: true, mw: "dealmaker" }, type: IssueType.SP },
  deal_making: { regex: /deal-making/ig, ui: { label: "deal-making", toLabel: "dealmaking", copyLabels: true, mw: "dealmaking" }, type: IssueType.SP },
  deep_fry: { regex: /deep fry/ig, ui: { label: "deep fry", toLabel: "deep-fry", copyLabels: true, mw: "deep-fry" }, type: IssueType.SP },
  defence: { regex: /defence/ig, ui: { label: "defence", toLabel: "defense", copyLabels: true, mw: "defense" }, type: IssueType.SP },
  dejavu: { regex: /deja vu/ig, ui: { label: "deja vu", toLabel: "déjà vu", copyLabels: true, mw: "déjà vu" }, type: IssueType.SP },
  descendent: { regex: /descendent/ig, ui: { label: "descendent", toLabel: "descendant", copyLabels: true, mw: "descendant" }, type: IssueType.SP },
  dieing: { regex: /dieing/ig, ui: { label: "dieing", toLabel: "dying", copyLabels: true }, type: IssueType.SP },
  dinner_time: { regex: /dinner time/ig, ui: { label: "dinner time", toLabel: "dinnertime", copyLabels: true, mw: "dinnertime" }, type: IssueType.SP },
  discernable: { regex: /discernable/ig, ui: { label: "discernable", toLabel: "discernible", copyLabels: true, mw: "discernible" }, type: IssueType.SP },
  discernably: { regex: /discernably/ig, ui: { label: "discernably", toLabel: "discernibly", copyLabels: true, mw: "discernibly" }, type: IssueType.SP },
  discreet: { regex: /discreet/ig, ui: { label: "discreet (discrete?)", copy: "discreet", }, type: IssueType.SP },
  discrete: { regex: /discrete/ig, ui: { label: "discrete (discreet?)", copy: "discrete" }, type: IssueType.SP },
  doppelganger: { regex: /doppelganger/ig, ui: { label: "doppelganger", toLabel: "doppelgänger", copyLabels: true, mw: "doppelgänger" }, type: IssueType.SP },
  doppleganger: { regex: /doppleganger/ig, ui: { label: "doppleganger", toLabel: "doppelgänger", copyLabels: true, mw: "doppelgänger" }, type: IssueType.SP },
  double_take: { regex: /double-take/ig, ui: { label: "double-take", toLabel: "double take", copyLabels: true, mw: "double take" }, type: IssueType.SP },
  doubletake: { regex: /doubletake/ig, ui: { label: "doubletake", toLabel: "double take", copyLabels: true, mw: "double take" }, type: IssueType.SP },
  draw_string: { regex: /draw string/ig, ui: { label: "draw string", toLabel: "drawstring (noun?)", copy: "draw string", paste: "drawstring", mw: "drawstring" }, type: IssueType.SP },
  dream_world: { regex: /dream world/ig, ui: { label: "dream world", toLabel: "dreamworld (noun?)", copy: "dream world", paste: "dreamworld", mw: "dreamworld" }, type: IssueType.SP },
  dream_world2: { regex: /dream-world/ig, ui: { label: "dream-world", toLabel: "dreamworld (noun?)", copy: "dream-world", paste: "dreamworld", mw: "dreamworld" }, type: IssueType.SP },
  drop_out: { regex: /drop-out/ig, ui: { label: "drop-out", toLabel: "dropout", copyLabels: true, mw: "dropout" }, type: IssueType.SP },
  drier: { regex: /drier/ig, ui: { label: "drier (adjective)", copy: "drier" }, type: IssueType.SP },
  dryer: { regex: /dryer/ig, ui: { label: "dryer (appliance)", copy: "dryer" }, type: IssueType.SP },
  duty_bound: { regex: /duty-bound/ig, ui: { label: "duty-bound", toLabel: "duty bound", copyLabels: true, mw: "duty bound" }, type: IssueType.SP },
  emphasise: { regex: /emphasise/ig, ui: { label: "emphasise", toLabel: "emphasize", copyLabels: true, mw: "emphasize" }, type: IssueType.SP },
  emphasising: { regex: /emphasising/ig, ui: { label: "emphasising", toLabel: "emphasizing", copyLabels: true, mw: "emphasize" }, type: IssueType.SP },
  enroute: { regex: /enroute/ig, ui: { label: "enroute", toLabel: "en route", copyLabels: true, mw: "en route" }, type: IssueType.SP },
  entree: { regex: /entree/ig, ui: { label: "entree", toLabel: "entrée", copyLabels: true, mw: "entrée" }, type: IssueType.SP },
  ever_so: { regex: /ever-so/ig, ui: { label: "ever-so", toLabel: "ever so", copyLabels: true, mw: "ever so" }, type: IssueType.SP },
  eyepatch: { regex: /eyepatch/ig, ui: { label: "eyepatch", toLabel: "eye patch", copyLabels: true }, type: IssueType.SP },
  eye_patch: { regex: /eye-patch/ig, ui: { label: "eye-patch", toLabel: "eye patch", copyLabels: true }, type: IssueType.SP },
  eye_to_eye: { regex: /eye-to-eye/ig, ui: { label: "eye-to-eye", toLabel: "eye to eye", copyLabels: true, mw: "see eye to eye" }, type: IssueType.SP },
  eye_witness: { regex: /eye witness/ig, ui: { label: "eye witness", toLabel: "eyewitness", copyLabels: true, mw: "eyewitness" }, type: IssueType.SP },
  eye_witness2: { regex: /eye-witness/ig, ui: { label: "eye-witness", toLabel: "eyewitness", copyLabels: true, mw: "eyewitness" }, type: IssueType.SP },
  
  // F through J
  face_down: { regex: /face down/ig, ui: { label: "face down", toLabel: "facedown (adjective?)", copy: "face down", paste: "facedown", mw: "facedown" }, type: IssueType.SP },
  face_down2: { regex: /face-down/ig, ui: { label: "face-down", toLabel: "facedown", copyLabels: true, mw: "facedown" }, type: IssueType.SP },
  face_to_face: { regex: /face to face/ig, ui: { label: "face to face", toLabel: "face-to-face", copyLabels: true, mw: "face-to-face" }, type: IssueType.SP },
  farsight: { regex: /farsight/ig, ui: { label: "farsight", toLabel: "far-sight", copyLabels: true, mw: "far-sight" }, type: IssueType.SP },
  fast_food: { regex: /fast-food/ig, ui: { label: "fast-food", toLabel: "fast food (noun?)", copy: "fast-food", paste: "fast food", mw: "fast food" }, type: IssueType.SP },
  fast_food2: { regex: /fast food/ig, ui: { label: "fast food", toLabel: "fast-food (adjective?)", copy: "fast food", paste: "fast-food", mw: "fast-food" }, type: IssueType.SP },
  fiance: { regex: /\bfiance[^e]/ig, ui: { label: "fiance", toLabel: "fiancé", copy: "\\bfiance[^e]", paste: "fiancé", mw: "fiancé" }, type: IssueType.SP },
  fiancee: { regex: /fiancee/ig, ui: { label: "fiancee", toLabel: "fiancée", copyLabels: true, mw: "fiancée" }, type: IssueType.SP },
  filet: { regex: /filet/ig, ui: { label: "filet (lace?)", toLabel: "fillet (meat?)", copy: "filet", paste: "fillet", mw: "fillet" }, type: IssueType.SP },
  fine_tune: { regex: /fine tune/ig, ui: { label: "fine tune", toLabel: "fine-tune (verb?)", copy: "fine tune", paste: "fine-tune", mw: "fine-tune" }, type: IssueType.SP },
  fine_tuning: { regex: /fine tuning/ig, ui: { label: "fine tuning", toLabel: "fine-tuning (verb?)", copy: "fine tuning", paste: "fine-tuning", mw: "fine-tune" }, type: IssueType.SP },
  finger_like: { regex: /finger-like/ig, ui: { label: "finger-like", toLabel: "fingerlike", copyLabels: true, mw: "fingerlike" }, type: IssueType.SP },
  first_aid: { regex: /first-aid/ig, ui: { label: "first-aid", toLabel: "first aid", copyLabels: true, mw: "first aid" }, type: IssueType.SP },
  first_hand: { regex: /first-hand/ig, ui: { label: "first-hand", toLabel: "firsthand", copyLabels: true, mw: "firsthand" }, type: IssueType.SP },
  first_hand2: { regex: /first hand/ig, ui: { label: "first hand", toLabel: "firsthand (adjective?)", copy: "first hand", paste: "firsthand", mw: "firsthand" }, type: IssueType.SP },
  fist_fight: { regex: /fist-fight/ig, ui: { label: "fist-fight", toLabel: "fistfight", copyLabels: true, mw: "fistfight" }, type: IssueType.SP },
  fist_fight2: { regex: /fist fight/ig, ui: { label: "fist fight", toLabel: "fistfight", copyLabels: true, mw: "fistfight" }, type: IssueType.SP },
  fist_full: { regex: /fist full/ig, ui: { label: "fist full", toLabel: "fistful?", copy: "fist full", paste: "fistful", mw: "fistful" }, type: IssueType.SP },
  flipside: { regex: /flipside/ig, ui: { label: "flipside", toLabel: "flip side", copyLabels: true, mw: "flip side" }, type: IssueType.SP },
  followup: { regex: /followup/ig, ui: { label: "followup", toLabel: "follow-up", copyLabels: true, mw: "follow-up" }, type: IssueType.SP },
  footsoldier: { regex: /footsoldier/ig, ui: { label: "footsoldier", toLabel: "foot soldier", copyLabels: true, mw: "foot soldier" }, type: IssueType.SP },
  forcefield: { regex: /forcefield/ig, ui: { label: "forcefield", toLabel: "force field", copyLabels: true, mw: "force field" }, type: IssueType.SP },
  forego: { regex: /forego/ig, ui: { label: "forego", toLabel: "forgo", copyLabels: true, mw: "forgo" }, type: IssueType.SP },
  forewent: { regex: /forewent/ig, ui: { label: "forewent", toLabel: "forwent", copyLabels: true, mw: "forgo" }, type: IssueType.SP },
  form_fitting: { regex: /form-fitting/ig, ui: { label: "form-fitting", toLabel: "formfitting", copyLabels: true, mw: "formfitting" }, type: IssueType.SP },
  forsaw: { regex: /forsaw/ig, ui: { label: "forsaw", toLabel: "foresaw", copyLabels: true, mw: "foresee" }, type: IssueType.SP },
  forsee: { regex: /forsee/ig, ui: { label: "forsee", toLabel: "foresee", copyLabels: true, mw: "foresee" }, type: IssueType.SP },
  foul_mouthed: { regex: /foul-mouthed/ig, ui: { label: "foul-mouthed", toLabel: "foulmouthed", copyLabels: true, mw: "foulmouthed" }, type: IssueType.SP },
  free_fall: { regex: /free-fall/ig, ui: { label: "free-fall (verb)", copy: "free-fall", mw: "free-fall" }, type: IssueType.SP },
  free_fall2: { regex: /free fall/ig, ui: { label: "free fall (noun)", copy: "free fall", mw: "free fall" }, type: IssueType.SP },
  free_flowing: { regex: /free flowing/ig, ui: { label: "free flowing", toLabel: "free-flowing", copyLabels: true, mw: "free-flowing" }, type: IssueType.SP },
  free_spirited: { regex: /free spirited/ig, ui: { label: "free spirited", toLabel: "free-spirited", copyLabels: true, mw: "free-spirited" }, type: IssueType.SP },
  frontline1: { regex: /frontline/ig, ui: { label: "frontline (adjective)", copy: "frontline", mw: "frontline" }, type: IssueType.SP },
  frontline2: { regex: /front line/ig, ui: { label: "front line (noun)", copy: "front line", mw: "front line" }, type: IssueType.SP },
  frontlines: { regex: /frontlines/ig, ui: { label: "frontlines", toLabel: "front lines", copyLabels: true, mw: "front line" }, type: IssueType.SP },
  g_force: { regex: /\bg force/g, ui: { label: "g force", toLabel: "g-force", copyLabels: true, mw: "g-force" }, type: IssueType.SP },
  game_changer: { regex: /game-changer/ig, ui: { label: "game-changer", toLabel: "game changer", copyLabels: true, mw: "game changer" }, type: IssueType.SP },
  gamechanger: { regex: /gamechanger/ig, ui: { label: "gamechanger", toLabel: "game changer", copyLabels: true, mw: "game changer" }, type: IssueType.SP },
  gameplan: { regex: /gameplan/ig, ui: { label: "gameplan", toLabel: "game plan", copyLabels: true, mw: "game plan" }, type: IssueType.SP },
  gatling: { regex: /gatling gun/g, ui: { label: "gatling gun", toLabel: "Gatling gun", copyLabels: true, mw: "Gatling gun" }, type: IssueType.SP },
  geez: { regex: /\bgeez\b/ig, ui: { label: "geez", toLabel: "jeez", copy: "geez\\b", paste: "jeez", mw: "jeez" }, type: IssueType.SP },
  glovebox: { regex: /glovebox/ig, ui: { label: "glovebox", toLabel: "glove box", copyLabels: true, mw: "glove box" }, type: IssueType.SP },
  goodwill: { regex: /good will/ig, ui: { label: "good will", toLabel: "goodwill", copyLabels: true, mw: "goodwill" }, type: IssueType.SP },
  good_will: { regex: /good-will/ig, ui: { label: "good-will", toLabel: "goodwill", copyLabels: true, mw: "goodwill" }, type: IssueType.SP },
  great_grand: { regex: /great grand/ig, ui: { label: "great grand (relationship?)", toLabel: "great-grand", copy: "great grand", paste: "great-grand" }, type: IssueType.SP },
  grevious: { regex: /grevious/ig, ui: { label: "grevious", toLabel: "grievous", copyLabels: true, mw: "grievous" }, type: IssueType.SP },
  grey: { regex: /grey/ig, ui: { label: "grey", toLabel: "gray", copyLabels: true, mw: "gray" }, type: IssueType.SP },
  grinded: { regex: /grinded/ig, ui: { label: "grinded", toLabel: "ground", copyLabels: true, mw: "grind" }, type: IssueType.SP },
  grit: { regex: /\bgrit\b/ig, ui: { label: "grit (should be gritted, past tense?)", copy: "grit\\b" }, type: IssueType.SP },
  grownup: { regex: /grownup/ig, ui: { label: "grownup", toLabel: "grown-up", copyLabels: true, mw: "grown-up" }, type: IssueType.SP },
  guerrila: { regex: /guerrila/ig, ui: { label: "guerrila", toLabel: "guerrilla", copyLabels: true, mw: "guerrilla" }, type: IssueType.SP },
  guerilla: { regex: /guerilla/ig, ui: { label: "guerilla", toLabel: "guerrilla", copyLabels: true, mw: "guerrilla" }, type: IssueType.SP },
  gun_powder: { regex: /gun powder/ig, ui: { label: "gun powder", toLabel: "gunpowder", copyLabels: true, mw: "gunpowder" }, type: IssueType.SP },
  halfmoon: { regex: /halfmoon/ig, ui: { label: "halfmoon", toLabel: "half-moon", copyLabels: true, mw: "half-moon" }, type: IssueType.SP },
  half_moon: { regex: /half moon/ig, ui: { label: "half moon", toLabel: "half-moon", copyLabels: true, mw: "half-moon" }, type: IssueType.SP },
  halftruth: { regex: /halftruth/ig, ui: { label: "halftruth", toLabel: "half-truth", copyLabels: true, mw: "half-truth" }, type: IssueType.SP },
  half_truth: { regex: /half truth/ig, ui: { label: "half truth", toLabel: "half-truth", copyLabels: true, mw: "half-truth" }, type: IssueType.SP },
  halfwit: { regex: /halfwit/ig, ui: { label: "halfwit", toLabel: "half-wit", copyLabels: true, mw: "half-wit" }, type: IssueType.SP },
  hand_in_hand: { regex: /hand-in-hand/ig, ui: { label: "hand-in-hand", toLabel: "hand in hand", copyLabels: true, mw: "hand in hand" }, type: IssueType.SP },
  hand_pick: { regex: /hand-pick/ig, ui: { label: "hand-pick", toLabel: "handpick", copyLabels: true, mw: "handpick" }, type: IssueType.SP },
  hard_and_fast: { regex: /hard and fast/ig, ui: { label: "hard and fast", toLabel: "hard-and-fast (adjective?)", copy: "hard and fast", paste: "hard-and-fast", mw: "hard-and-fast" }, type: IssueType.SP },
  hardpressed: { regex: /hardpressed/ig, ui: { label: "hardpressed", toLabel: "hard-pressed", copyLabels: true, mw: "hard-pressed" }, type: IssueType.SP },
  hard_working: { regex: /hard-working/ig, ui: { label: "hard-working", toLabel: "hardworking", copyLabels: true, mw: "hardworking" }, type: IssueType.SP },
  head_on: { regex: /\bhead on\b/ig, ui: { label: "head on", toLabel: "head-on (adverb?)", copy: "\\bhead on\\b", paste: "head-on", mw: "head-on" }, type: IssueType.SP },
  head_scratcher: { regex: /head scratcher/ig, ui: { label: "head scratcher", toLabel: "head-scratcher", copyLabels: true, mw: "head-scratcher" }, type: IssueType.SP },
  heroin: { regex: /heroin[^e]/ig, ui: { label: "heroin (heroine?)", copy: "heroin\\e" }, type: IssueType.SP },
  high_five: { regex: /high five/ig, ui: { label: "high five (noun)", copy: "high five", mw: "high five" }, type: IssueType.SP },
  high_five2: { regex: /high-five/ig, ui: { label: "high-five (verb)", copy: "high-five", mw: "high-five" }, type: IssueType.SP },
  higher_ups: { regex: /higher ups/ig, ui: { label: "higher ups", toLabel: "higher-ups", copyLabels: true, mw: "higher-up" }, type: IssueType.SP },
  high_performance: { regex: /high-performance/ig, ui: { label: "high-performance", toLabel: "high performance", copyLabels: true, mw: "high performance" }, type: IssueType.SP },
  high_schooler: { regex: /high-schooler/ig, ui: { label: "high-schooler", toLabel: "high schooler", copyLabels: true, mw: "high schooler" }, type: IssueType.SP },
  hitman: { regex: /hitman/ig, ui: { label: "hitman", toLabel: "hit man", copyLabels: true, mw: "hit man" }, type: IssueType.SP },
  home_made: { regex: /home-made/ig, ui: { label: "home-made", toLabel: "homemade", copyLabels: true, mw: "homemade" }, type: IssueType.SP },
  home_sick: { regex: /home sick/ig, ui: { label: "home sick", toLabel: "homesick (adjective?)", copy: "home sick", paste: "homesick", mw: "homesick" }, type: IssueType.SP },
  home_sick2: { regex: /home-sick/ig, ui: { label: "home-sick", toLabel: "homesick", copyLabels: true, mw: "homesick" }, type: IssueType.SP },
  human_like: { regex: /human-like/ig, ui: { label: "human-like", toLabel: "humanlike", copyLabels: true, mw: "humanlike" }, type: IssueType.SP },
  ice_cream_cone: { regex: /ice cream cone/ig, ui: { label: "ice cream cone", toLabel: "ice-cream cone", copyLabels: true, mw: "ice-cream cone" }, type: IssueType.SP },
  icepack: { regex: /icepack/ig, ui: { label: "icepack", toLabel: "ice pack", copyLabels: true, mw: "ice pack" }, type: IssueType.SP },
  iron_clad: { regex: /iron-clad/ig, ui: { label: "iron-clad", toLabel: "ironclad", copyLabels: true, mw: "ironclad" }, type: IssueType.SP },
  iron_fisted: { regex: /iron-fisted/ig, ui: { label: "iron-fisted", toLabel: "ironfisted", copyLabels: true, mw: "ironfisted" }, type: IssueType.SP },
  judge: { regex: /judgement/ig, ui: { label: "judgement", toLabel: "judgment", copyLabels: true, mw: "judgment" }, type: IssueType.SP },
  jungle_like: { regex: /jungle-like/ig, ui: { label: "jungle-like", toLabel: "junglelike", copyLabels: true, mw: "junglelike" }, type: IssueType.SP },
  
  // K through O
  kickstart: { regex: /kickstart/ig, ui: { label: "kickstart", toLabel: "kick-start", copyLabels: true, mw: "kick-start" }, type: IssueType.SP },
  kind_hearted: { regex: /kind-hearted/ig, ui: { label: "kind-hearted", toLabel: "kindhearted", copyLabels: true, mw: "kindhearted" }, type: IssueType.SP },
  kind_hearted2: { regex: /kind hearted/ig, ui: { label: "kind hearted", toLabel: "kindhearted", copyLabels: true, mw: "kindhearted" }, type: IssueType.SP },
  knock_off: { regex: /knock-off/ig, ui: { label: "knock-off", toLabel: "knockoff", copyLabels: true, mw: "knockoff" }, type: IssueType.SP },
  knowhow: { regex: /knowhow/ig, ui: { label: "knowhow", toLabel: "know-how", copyLabels: true, mw: "know-how" }, type: IssueType.SP },
  laidback: { regex: /laidback/ig, ui: { label: "laidback", toLabel: "laid-back", copyLabels: true, mw: "laid-back" }, type: IssueType.SP },
  landmine: { regex: /landmine/ig, ui: { label: "landmine", toLabel: "land mine", copyLabels: true, mw: "land mine" }, type: IssueType.SP },
  last_ditch: { regex: /last ditch/ig, ui: { label: "last ditch (noun)", mw: "last ditch" }, type: IssueType.SP },
  last_ditch2: { regex: /last-ditch/ig, ui: { label: "last-ditch (adjective)", mw: "last-ditch" }, type: IssueType.SP },
  laugh1: { regex: /haha/ig, ui: { label: "haha", toLabel: "ha ha", copyLabels: true }, type: IssueType.SP },
  laugh2: { regex: /heehee/ig, ui: { label: "heehee", toLabel: "hee hee", copyLabels: true }, type: IssueType.SP },
  lead: { regex: /\blead\b/ig, ui: { label: "lead (should be led, past tense?)", copy: "\\blead\\b" }, type: IssueType.SP },
  let_down: { regex: /let-down/ig, ui: { label: "let-down", toLabel: "letdown", copyLabels: true, mw: "letdown" }, type: IssueType.SP },
  life_and_death: { regex: /life and death/ig, ui: { label: "life and death", toLabel: "life-and-death (adjective?)", copy: "life and death", paste: "life-and-death", mw: "life-and-death" }, type: IssueType.SP },
  life_blood: { regex: /life-blood/ig, ui: { label: "life-blood", toLabel: "lifeblood", copyLabels: true, mw: "lifeblood" }, type: IssueType.SP },
  life_form: { regex: /life form/ig, ui: { label: "life form", toLabel: "life-form", copyLabels: true, mw: "life-form" }, type: IssueType.SP },
  lifeform: { regex: /lifeform/ig, ui: { label: "lifeform", toLabel: "life-form", copyLabels: true, mw: "life-form" }, type: IssueType.SP },
  life_span: { regex: /life-span/ig, ui: { label: "life-span", toLabel: "life span", copyLabels: true, mw: "life span" }, type: IssueType.SP },
  lifespan: { regex: /lifespan/ig, ui: { label: "lifespan", toLabel: "life span", copyLabels: true, mw: "life span" }, type: IssueType.SP },
  life_threatening: { regex: /life threatening/ig, ui: { label: "life threatening", toLabel: "life-threatening", copyLabels: true, mw: "life-threatening" }, type: IssueType.SP },
  light_headed: { regex: /light headed/ig, ui: { label: "light headed", toLabel: "light-headed", copyLabels: true, mw: "light-headed" }, type: IssueType.SP },
  lightheaded: { regex: /lightheaded/ig, ui: { label: "lightheaded", toLabel: "light-headed", copyLabels: true, mw: "light-headed" }, type: IssueType.SP },
  light_hearted: { regex: /light-hearted/ig, ui: { label: "light-hearted", toLabel: "lighthearted", copyLabels: true, mw: "lighthearted" }, type: IssueType.SP },
  light_hearted2: { regex: /light hearted/ig, ui: { label: "light hearted", toLabel: "lighthearted", copyLabels: true, mw: "lighthearted" }, type: IssueType.SP },
  light_weight: { regex: /light-weight/ig, ui: { label: "light-weight", toLabel: "lightweight", copyLabels: true, mw: "lightweight" }, type: IssueType.SP },
  line_up: { regex: /line-up/ig, ui: { label: "line-up", toLabel: "lineup", copyLabels: true, mw: "lineup" }, type: IssueType.SP },
  liquif: { regex: /liquif(y|ied)/ig, ui: { label: "liquif(y, ied)", toLabel: "liquef(y, ied)", copy: "liquif(y|ied)", mw: "liquefy" }, type: IssueType.SP },
  longshot: { regex: /longshot/ig, ui: { label: "longshot", toLabel: "long shot", copyLabels: true, mw: "long shot" }, type: IssueType.SP },
  long_shot: { regex: /long-shot/ig, ui: { label: "long-shot", toLabel: "long shot", copyLabels: true, mw: "long shot" }, type: IssueType.SP },
  long_time: { regex: /long-time/ig, ui: { label: "long-time", toLabel: "longtime", copyLabels: true, mw: "longtime" }, type: IssueType.SP },
  lookalike: { regex: /lookalike/ig, ui: { label: "lookalike", toLabel: "look-alike", copyLabels: true, mw: "look-alike" }, type: IssueType.SP },
  love_struck: { regex: /love-struck/ig, ui: { label: "love-struck", toLabel: "lovestruck", copyLabels: true, mw: "lovestruck" }, type: IssueType.SP },
  lunchbox: { regex: /lunchbox/ig, ui: { label: "lunchbox", toLabel: "lunch box", copyLabels: true, mw: "lunch box" }, type: IssueType.SP },
  keychain: { regex: /keychain/ig, ui: { label: "keychain", toLabel: "key chain", copyLabels: true, mw: "key chain" }, type: IssueType.SP },
  lightbulb: { regex: /lightbulb/ig, ui: { label: "lightbulb", toLabel: "light bulb", copyLabels: true, mw: "light bulb" }, type: IssueType.SP },
  make_due: { regex: /make due/ig, ui: { label: "make due", toLabel: "make do", copyLabels: true, mw: "make do" }, type: IssueType.SP },
  make_up: { regex: /make-up/ig, ui: { label: "make-up", toLabel: "makeup", copyLabels: true, mw: "makeup" }, type: IssueType.SP },
  manmade: { regex: /manmade/ig, ui: { label: "manmade", toLabel: "man-made", copyLabels: true, mw: "man-made" }, type: IssueType.SP },
  manpower: { regex: /manpower/ig, ui: { label: "manpower", toLabel: "man power", copyLabels: true, mw: "man power" }, type: IssueType.SP },
  mask_like: { regex: /mask-like/ig, ui: { label: "mask-like", toLabel: "masklike", copyLabels: true, mw: "masklike" }, type: IssueType.SP },
  mass_produce: { regex: /mass produce/ig, ui: { label: "mass produce", toLabel: "mass-produce", copyLabels: true, mw: "mass-produce" }, type: IssueType.SP },
  mass_producing: { regex: /mass producing/ig, ui: { label: "mass producing", toLabel: "mass-producing", copyLabels: true, mw: "mass-produce" }, type: IssueType.SP },
  mass_production: { regex: /mass-production/ig, ui: { label: "mass-production", toLabel: "mass production", copyLabels: true, mw: "mass production" }, type: IssueType.SP },
  meagre: { regex: /meagre/ig, ui: { label: "meagre", toLabel: "meager", copyLabels: true, mw: "meager" }, type: IssueType.SP },
  mid_air: { regex: /mid-air/ig, ui: { label: "mid-air", toLabel: "midair", copyLabels: true, mw: "midair" }, type: IssueType.SP },
  mid_morning: { regex: /mid-morning/i, ui: { label: "mid-morning", toLabel: "midmorning", copyLabels: true, mw: "midmorning" }, type: IssueType.SP },
  mid_point: { regex: /mid-point/ig, ui: { label: "mid-point", toLabel: "midpoint", copyLabels: true, mw: "midpoint" }, type: IssueType.SP },
  mid_section: { regex: /mid-section/ig, ui: { label: "mid-section", toLabel: "midsection", copyLabels: true, mw: "midsection" }, type: IssueType.SP },
  mid_sentence: { regex: /mid-sentence/ig, ui: { label: "mid-sentence", toLabel: "midsentence", copyLabels: true }, type: IssueType.SP },
  mid_forties: { regex: /mid-forties/ig, ui: { label: "mid-forties", toLabel: "midforties", copyLabels: true }, type: IssueType.SP },
  mid_thirties: { regex: /mid-thirties/ig, ui: { label: "mid-thirties", toLabel: "midthirties", copyLabels: true }, type: IssueType.SP },
  mid_twenties: { regex: /mid-twenties/ig, ui: { label: "mid-twenties", toLabel: "midtwenties", copyLabels: true }, type: IssueType.SP },
  mini_car: { regex: /mini-car/ig, ui: { label: "mini-car", toLabel: "minicar", copyLabels: true, mw: "minicar" }, type: IssueType.SP },
  miniscule: { regex: /miniscule/ig, ui: { label: "miniscule", toLabel: "minuscule", copyLabels: true, mw: "minuscule" }, type: IssueType.SP },
  mischevious: { regex: /mischevious/ig, ui: { label: "mischevious", toLabel: "mischievous", copyLabels: true, mw: "mischievous" }, type: IssueType.SP },
  month_long: { regex: /month-long/ig, ui: { label: "month-long", toLabel: "monthlong", copyLabels: true, mw: "monthlong" }, type: IssueType.SP },
  mothership: { regex: /mothership/ig, ui: { label: "mothership", toLabel: "mother ship", copyLabels: true, mw: "mother ship" }, type: IssueType.SP },
  moustache: { regex: /moustache/ig, ui: { label: "moustache", toLabel: "mustache", copyLabels: true, mw: "mustache" }, type: IssueType.SP },
  naive: { regex: /naïve/ig, ui: { label: "naïve", toLabel: "naive", copyLabels: true, mw: "naive" }, type: IssueType.SP },
  name_drop: { regex: /name drop/ig, ui: { label: "name drop", toLabel: "name-drop", copyLabels: true, mw: "name-drop" }, type: IssueType.SP },
  neverending: { regex: /neverending/ig, ui: { label: "neverending", toLabel: "never-ending", copyLabels: true, mw: "never-ending" }, type: IssueType.SP },
  nm: { regex: /nevermind/ig, ui: { label: "nevermind", toLabel: "never mind", copyLabels: true, mw: "never mind" }, type: IssueType.SP },
  non_answer: { regex: /non-answer/ig, ui: { label: "non-answer", toLabel: "nonanswer", copyLabels: true, mw: "nonanswer" }, type: IssueType.SP },
  non_combatant: { regex: /non-combatant/ig, ui: { label: "non-combatant", toLabel: "noncombatant", copyLabels: true, mw: "noncombatant" }, type: IssueType.SP },
  non_committal: { regex: /non-committal/ig, ui: { label: "non-committal", toLabel: "noncommittal", copyLabels: true, mw: "noncommittal" }, type: IssueType.SP },
  non_confrontational: { regex: /non-confrontational/ig, ui: { label: "non-confrontational", toLabel: "nonconfrontational", copyLabels: true, mw: "nonconfrontational" }, type: IssueType.SP },
  non_existent: { regex: /non-existent/ig, ui: { label: "non-existent", toLabel: "nonexistent", copyLabels: true, mw: "nonexistent" }, type: IssueType.SP },
  non_hero: { regex: /non-hero/ig, ui: { label: "non-hero", toLabel: "nonhero", copyLabels: true, mw: "nonhero" }, type: IssueType.SP },
  non_living: { regex: /non-living/ig, ui: { label: "non-living", toLabel: "nonliving", copyLabels: true, mw: "nonliving" }, type: IssueType.SP },
  non_participant: { regex: /non-participant/ig, ui: { label: "non-participant", toLabel: "nonparticipant", copyLabels: true, mw: "nonparticipant" }, type: IssueType.SP },
  non_sequitur: { regex: /non-sequitur/ig, ui: { label: "non-sequitur", toLabel: "non sequitur", copyLabels: true, mw: "non sequitur" }, type: IssueType.SP },
  nonsequitur: { regex: /nonsequitur/ig, ui: { label: "nonsequitur", toLabel: "non sequitur", copyLabels: true, mw: "non sequitur" }, type: IssueType.SP },
  non_stop: { regex: /non-stop/ig, ui: { label: "non-stop", toLabel: "nonstop", copyLabels: true, mw: "nonstop" }, type: IssueType.SP },
  non_zero: { regex: /non-zero/ig, ui: { label: "non-zero", toLabel: "nonzero", copyLabels: true, mw: "nonzero" }, type: IssueType.SP },
  notetaking: { regex: /notetaking/ig, ui: { label: "notetaking", toLabel: "note-taking", copyLabels: true, mw: "note-taking" }, type: IssueType.SP },
  note_taking: { regex: /note taking/ig, ui: { label: "note taking", toLabel: "note-taking", copyLabels: true, mw: "note-taking" }, type: IssueType.SP },
  number_one: { regex: /number-one/ig, ui: { label: "number-one", toLabel: "number one", copyLabels: true, mw: "number one" }, type: IssueType.SP },
  ocher: { regex: /ochre/ig, ui: { label: "ochre", toLabel: "ocher", copyLabels: true, mw: "ocher" }, type: IssueType.SP },
  occured: { regex: /occured/ig, ui: { label: "occured", toLabel: "occurred", copyLabels: true, mw: "occur" }, type: IssueType.SP },
  occuring: { regex: /occuring/ig, ui: { label: "occuring", toLabel: "occurring", copyLabels: true, mw: "occur" }, type: IssueType.SP },
  offence: { regex: /offence/ig, ui: { label: "offence", toLabel: "offense", copyLabels: true, mw: "offense" }, type: IssueType.SP },
  off_balance: { regex: /off balance/ig, ui: { label: "off balance", toLabel: "off-balance", copyLabels: true, mw: "off-balance" }, type: IssueType.SP },
  off_duty: { regex: /off-duty/ig, ui: { label: "off-duty", toLabel: "off duty", copyLabels: true, mw: "off duty" }, type: IssueType.SP },
  off_guard: { regex: /off-guard/ig, ui: { label: "off-guard", toLabel: "off guard", copyLabels: true, mw: "off guard" }, type: IssueType.SP },
  off_handed: { regex: /off-handed/ig, ui: { label: "off-handed", toLabel: "offhanded", copyLabels: true, mw: "offhanded" }, type: IssueType.SP },
  offload: { regex: /offload/ig, ui: { label: "offload", toLabel: "off-load", copyLabels: true, mw: "off-load" }, type: IssueType.SP },
  omelette: { regex: /omelette/ig, ui: { label: "omelette", toLabel: "omelet", copyLabels: true, mw: "omelet" }, type: IssueType.SP },
  on_screen: { regex: /on screen/ig, ui: { label: "on screen", toLabel: "on-screen", copyLabels: true, mw: "on-screen" }, type: IssueType.SP },
  onscreen: { regex: /onscreen/ig, ui: { label: "onscreen", toLabel: "on-screen", copyLabels: true, mw: "on-screen" }, type: IssueType.SP },
  on_stage: { regex: /on-stage/ig, ui: { label: "on-stage", toLabel: "onstage", copyLabels: true, mw: "onstage" }, type: IssueType.SP },
  on_stage2: { regex: /on stage/ig, ui: { label: "on stage", toLabel: "onstage", copyLabels: true, mw: "onstage" }, type: IssueType.SP },
  one_time: { regex: /one-time/ig, ui: { label: "one-time", toLabel: "onetime", copyLabels: true, mw: "onetime" }, type: IssueType.SP },
  over_excited: { regex: /over-excited/ig, ui: { label: "over-excited", toLabel: "overexcited", copyLabels: true, mw: "overexcited" }, type: IssueType.SP },
  over_extend: { regex: /over-extend/ig, ui: { label: "over-extend", toLabel: "overextend", copyLabels: true, mw: "overextend" }, type: IssueType.SP },
  over_familiar: { regex: /over-familiar/ig, ui: { label: "over-familiar", toLabel: "overfamiliar", copyLabels: true, mw: "overfamiliar" }, type: IssueType.SP },
  over_prepared: { regex: /over-prepared/ig, ui: { label: "over-prepared", toLabel: "overprepared", copyLabels: true, mw: "overprepared" }, type: IssueType.SP },
  over_protect: { regex: /over-protect/ig, ui: { label: "over-protect", toLabel: "overprotect", copyLabels: true, mw: "overprotect" }, type: IssueType.SP },
  
  // P through T
  part_timer: { regex: /part timer/ig, ui: { label: "part timer", toLabel: "part-timer", copyLabels: true, mw: "part-timer" }, type: IssueType.SP },
  paper_mache: { regex: /paper mache/ig, ui: { label: "paper mache", toLabel: "paper-mache or papier mâché", copy: "paper mache", mw: "paper-mache" }, type: IssueType.SP },
  phase: { regex: /phase/ig, ui: { label: "phase", toLabel: "faze (verb?)", copy: "phase", paste: "faze", mw: "faze" }, type: IssueType.SP },
  photoshoot: { regex: /photoshoot/ig, ui: { label: "photoshoot", toLabel: "photo shoot", copyLabels: true, mw: "photo shoot" }, type: IssueType.SP },
  piecede: { regex: /piece de resistance/ig, ui: { label: "piece de resistance", toLabel: "pièce de résistance", copyLabels: true, mw: "pièce de résistance" }, type: IssueType.SP },
  pipsqueak: { regex: /pipsqueak/ig, ui: { label: "pipsqueak", toLabel: "pip-squeak", copyLabels: true, mw: "pip-squeak" }, type: IssueType.SP },
  plain_clothes: { regex: /plain-clothes/ig, ui: { label: "plain-clothes", toLabel: "plainclothes", copyLabels: true, mw: "plainclothes" }, type: IssueType.SP },
  plantlife: { regex: /plantlife/ig, ui: { label: "plantlife", toLabel: "plant life", copyLabels: true, mw: "plant life" }, type: IssueType.SP },
  plough: { regex: /plough/ig, ui: { label: "plough", toLabel: "plow", copyLabels: true, mw: "plow" }, type: IssueType.SP },
  point_blank: { regex: /point blank/ig, ui: { label: "point blank", toLabel: "point-blank", copyLabels: true, mw: "point-blank" }, type: IssueType.SP },
  power_walk: { regex: /power-walk/ig, ui: { label: "power-walk", toLabel: "power walk", copyLabels: true, mw: "power walk" }, type: IssueType.SP },
  principal: { regex: /principal/ig, ui: { label: "principal (head of a school)", copy: "principal" }, type: IssueType.SP },
  principle: { regex: /principle/ig, ui: { label: "principle (concept)", copy: "principle" }, type: IssueType.SP },
  psych: { regex: /psych[^e]\b/ig, ui: { label: "psych (verb)", copy: "\\bpsych[^e]\\b" }, type: IssueType.SP },
  psyche: { regex: /\bpsyche/ig, ui: { label: "psyche (noun)", copy: "\\bpsyche" }, type: IssueType.SP },
  pubic: { regex: /pubic/ig, ui: { label: "pubic (public?)", copy: "pubic" }, type: IssueType.SP },
  publically: { regex: /publically/ig, ui: { label: "publically", toLabel: "publicly", copyLabels: true, mw: "publicly" }, type: IssueType.SP },
  punchline: { regex: /punchline/ig, ui: { label: "punchline", toLabel: "punch line", copyLabels: true, mw: "punch line" }, type: IssueType.SP },
  punch_line: { regex: /punch-line/ig, ui: { label: "punch-line", toLabel: "punch line", copyLabels: true, mw: "punch line" }, type: IssueType.SP },
  puppet_like: { regex: /puppet-like/ig, ui: { label: "puppet-like", toLabel: "puppetlike", copyLabels: true, mw: "puppetlike" }, type: IssueType.SP },
  pureblooded: { regex: /pureblooded/ig, ui: { label: "pureblooded", toLabel: "pure-blooded", copyLabels: true, mw: "pure-blooded" }, type: IssueType.SP },
  pushup: { regex: /pushup/ig, ui: { label: "pushup", toLabel: "push-up", copyLabels: true, mw: "push-up" }, type: IssueType.SP }, 
  ragdoll: { regex: /ragdoll/ig, ui: { label: "ragdoll", toLabel: "rag doll", copyLabels: true, mw: "rag doll" }, type: IssueType.SP },
  rag_tag: { regex: /rag-tag/ig, ui: { label: "rag-tag", toLabel: "ragtag", copyLabels: true, mw: "ragtag" }, type: IssueType.SP },
  railgun: { regex: /railgun/ig, ui: { label: "railgun", toLabel: "rail gun", copyLabels: true, mw: "rail gun" }, type: IssueType.SP },
  rear_view_mirror: { regex: /rear view mirror/ig, ui: { label: "rear view mirror", toLabel: "rearview mirror", copyLabels: true, mw: "rearview mirror" }, type: IssueType.SP },
  rear_view_mirror2: { regex: /rear-view mirror/ig, ui: { label: "rear-view mirror", toLabel: "rearview mirror", copyLabels: true, mw: "rearview mirror" }, type: IssueType.SP },
  re_absorb: { regex: /re-absorb/ig, ui: { label: "re-absorb", toLabel: "reabsorb", copyLabels: true, mw: "reabsorb" }, type: IssueType.SP },
  re_categorize: { regex: /re-categorize/ig, ui: { label: "re-categorize", toLabel: "recategorize", copyLabels: true, mw: "recategorize" }, type: IssueType.SP },
  re_enact: { regex: /re-enact/ig, ui: { label: "re-enact", toLabel: "reenact", copyLabels: true, mw: "reenact" }, type: IssueType.SP },
  re_evaluate: { regex: /re-evaluate/ig, ui: { label: "re-evaluate", toLabel: "reevaluate", copyLabels: true, mw: "reevaluate" }, type: IssueType.SP },
  re_examine: { regex: /re-examine/ig, ui: { label: "re-examine", toLabel: "reexamine", copyLabels: true, mw: "reexamine" }, type: IssueType.SP },
  red_faced: { regex: /red faced/ig, ui: { label: "red faced", toLabel: "red-faced", copyLabels: true, mw: "red-faced" }, type: IssueType.SP },
  ribcage: { regex: /ribcage/ig, ui: { label: "ribcage", toLabel: "rib cage", copyLabels: true, mw: "rib cage" }, type: IssueType.SP },
  rip: { regex: /\br\.i\.p\.?\b/ig, ui: { label: "R.I.P", toLabel: "RIP", copyLabels: true, mw: "RIP" }, type: IssueType.SP },
  risque: { regex: /risque/ig, ui: { label: "risque", toLabel: "risqué", copyLabels: true, mw: "risqué" }, type: IssueType.SP },
  river_bank: { regex: /river bank/ig, ui: { label: "river bank", toLabel: "riverbank", copyLabels: true, mw: "riverbank" }, type: IssueType.SP },
  river_bank2: { regex: /river-bank/ig, ui: { label: "river-bank", toLabel: "riverbank", copyLabels: true, mw: "riverbank" }, type: IssueType.SP },
  role_play: { regex: /role play/ig, ui: { label: "role play", toLabel: "role-play (verb?)", copy: "role play", paste: "role-play", mw: "role-play" }, type: IssueType.SP },
  roleplay: { regex: /roleplay/ig, ui: { label: "roleplay", toLabel: "role-play", copyLabels: true, mw: "role-play" }, type: IssueType.SP },
  rough_and_tumble: { regex: /rough and tumble/ig, ui: { label: "rough and tumble", toLabel: "rough-and-tumble", copyLabels: true, mw: "rough-and-tumble" }, type: IssueType.SP },
  round_robin: { regex: /round robin/ig, ui: { label: "round robin", toLabel: "round-robin", copyLabels: true, mw: "round-robin" }, type: IssueType.SP },
  rundown: { regex: /rundown/ig, ui: { label: "rundown (noun)", copy: "rundown", mw: "rundown" }, type: IssueType.SP },
  run_down: { regex: /run-down/ig, ui: { label: "run-down (adjective)", copy: "run-down", mw: "run-down" }, type: IssueType.SP },
  run_down2: { regex: /run down/ig, ui: { label: "run down (verb)", copy: "run down", mw: "run down" }, type: IssueType.SP },
  run_in: { regex: /run in\b/ig, ui: { label: "run in (verb)", copy: "run in\\b", mw: "run in" }, type: IssueType.SP },
  run_in2: { regex: /run-in/ig, ui: { label: "run-in (noun)", copy: "run-in", mw: "run-in" }, type: IssueType.SP },
  saute: { regex: /saute/ig, ui: { label: "saute", toLabel: "sauté", copyLabels: true, mw: "sauté" }, type: IssueType.SP },
  saw_like: { regex: /saw-like/ig, ui: { label: "saw-like", toLabel: "sawlike", copyLabels: true, mw: "sawlike" }, type: IssueType.SP },
  seatbelt: { regex: /seatbelt/ig, ui: { label: "seatbelt", toLabel: "seat belt", copyLabels: true, mw: "seat belt" }, type: IssueType.SP },
  sea_water: { regex: /sea water/ig, ui: { label: "sea water", toLabel: "seawater", copyLabels: true, mw: "seawater" }, type: IssueType.SP },
  second_guess: { regex: /second guess/ig, ui: { label: "second guess", toLabel: "second-guess (verb?)", copyLabels: true, mw: "second-guess" }, type: IssueType.SP },
  second_hand: { regex: /second-hand/ig, ui: { label: "second-hand", toLabel: "secondhand", copyLabels: true, mw: "secondhand" }, type: IssueType.SP },
  self_expression: { regex: /self expression/ig, ui: { label: "self expression", toLabel: "self-expression", copyLabels: true, mw: "self-expression" }, type: IssueType.SP },
  semi_circle: { regex: /semi-circle/ig, ui: { label: "semi-circle", toLabel: "semicircle", copyLabels: true, mw: "semicircle" }, type: IssueType.SP },
  semi_translucent: { regex: /semi-translucent/ig, ui: { label: "semi-translucent", toLabel: "semitranslucent", copyLabels: true, mw: "semitranslucent" }, type: IssueType.SP },
  semi_transparent: { regex: /semi-transparent/ig, ui: { label: "semi-transparent", toLabel: "semitransparent", copyLabels: true, mw: "semitransparent" }, type: IssueType.SP },
  semi_truck: { regex: /semi truck/ig, ui: { label: "semi truck", toLabel: "semitruck", copyLabels: true, mw: "semitruck" }, type: IssueType.SP },
  semi_truck2: { regex: /semi-truck/ig, ui: { label: "semi-truck", toLabel: "semitruck", copyLabels: true, mw: "semitruck" }, type: IssueType.SP },
  shapeshift: { regex: /shapeshift/ig, ui: { label: "shapeshift", toLabel: "shape-shift", copyLabels: true, mw: "shape-shift" }, type: IssueType.SP },
  sheath: { regex: /sheath[^e]/ig, ui: { label: "sheath (noun)", copy: "sheath[^e]", mw: "sheath" }, type: IssueType.SP },
  sheathe: { regex: /sheathe/ig, ui: { label: "sheathe (verb)", copy: "sheathe", mw: "sheathe" }, type: IssueType.SP },
  shockwave: { regex: /shockwave/ig, ui: { label: "shockwave", toLabel: "shock wave", copyLabels: true, mw: "shock wave" }, type: IssueType.SP },
  short_sighted: { regex: /short-sighted/ig, ui: { label: "short-sighted", toLabel: "shortsighted", copyLabels: true, mw: "shortsighted" }, type: IssueType.SP },
  shuteye: { regex: /shuteye/ig, ui: { label: "shuteye", toLabel: "shut-eye", copyLabels: true, mw: "shut-eye" }, type: IssueType.SP },
  side_by_side: { regex: /side by side/ig, ui: { label: "side by side (adverb)", copy: "side by side", mw: "side by side" }, type: IssueType.SP },
  side_by_side2: { regex: /side-by-side/ig, ui: { label: "side-by-side (adjective)", toLabel: "side-by-side", mw: "shut-eye" }, type: IssueType.SP },
  signalling: { regex: /signalling/ig, ui: { label: "signalling", toLabel: "signaling", copyLabels: true, mw: "signal" }, type: IssueType.SP },
  silk_like: { regex: /silk-like/ig, ui: { label: "silk-like", toLabel: "silklike", copyLabels: true, mw: "silklike" }, type: IssueType.SP },
  simple_minded: { regex: /simple-minded/ig, ui: { label: "simple-minded", toLabel: "simpleminded", copyLabels: true, mw: "simpleminded" }, type: IssueType.SP },
  single_file: { regex: /single-file/ig, ui: { label: "single-file", toLabel: "single file", copyLabels: true, mw: "single file" }, type: IssueType.SP },
  singlehanded: { regex: /singlehanded/ig, ui: { label: "singlehanded", toLabel: "single-handed", copyLabels: true, mw: "single-handed" }, type: IssueType.SP },
  singleminded: { regex: /singleminded/ig, ui: { label: "singleminded", toLabel: "single-minded", copyLabels: true, mw: "single-minded" }, type: IssueType.SP },
  sizeable: { regex: /sizeable/ig, ui: { label: "sizeable", toLabel: "sizable", copyLabels: true, mw: "sizable" }, type: IssueType.SP },
  skillset: { regex: /skillset/ig, ui: { label: "skillset", toLabel: "skill set", copyLabels: true, mw: "skill set" }, type: IssueType.SP },
  slayed: { regex: /slayed/ig, ui: { label: "slayed (comedy?)", toLabel: "slew (murder?)", copy: "slayed", paste: "slew", mw: "slay" }, type: IssueType.SP },
  slip_up: { regex: /slip-up/ig, ui: { label: "slip-up", toLabel: "slipup", copyLabels: true, mw: "slipup" }, type: IssueType.SP },
  smokey: { regex: /smokey/ig, ui: { label: "smokey", toLabel: "smoky", copyLabels: true, mw: "smoky" }, type: IssueType.SP },
  smoulder: { regex: /smoulder/ig, ui: { label: "smoulder", toLabel: "smolder", copyLabels: true, mw: "smolder" }, type: IssueType.SP },
  smack_dab: { regex: /smack dab/ig, ui: { label: "smack dab", toLabel: "smack-dab", copyLabels: true, mw: "smack-dab" }, type: IssueType.SP },
  soft_hearted: { regex: /soft-hearted/ig, ui: { label: "soft-hearted", toLabel: "softhearted", copyLabels: true, mw: "softhearted" }, type: IssueType.SP },
  soft_serve: { regex: /soft-serve/ig, ui: { label: "soft-serve", toLabel: "soft serve", copyLabels: true, mw: "soft serve" }, type: IssueType.SP },
  soul: { regex: /soulmate/ig, ui: { label: "soulmate", toLabel: "soul mate", copyLabels: true, mw: "soul mate" }, type: IssueType.SP },
  spine_like: { regex: /spine-like/ig, ui: { label: "spine-like", toLabel: "spinelike", copyLabels: true, mw: "spinelike" }, type: IssueType.SP },
  standalone: { regex: /standalone/ig, ui: { label: "standalone", toLabel: "stand-alone", copyLabels: true, mw: "stand-alone" }, type: IssueType.SP },
  stand_out: { regex: /stand-out/ig, ui: { label: "stand-out", toLabel: "standout", copyLabels: true, mw: "standout" }, type: IssueType.SP },
  stepping_stone: { regex: /stepping-stone/ig, ui: { label: "stepping-stone", toLabel: "stepping stone", copyLabels: true, mw: "stepping stone" }, type: IssueType.SP },
  storyline: { regex: /storyline/ig, ui: { label: "storyline", toLabel: "story line", copyLabels: true, mw: "story line" }, type: IssueType.SP },
  strait: { regex: /straightlaced/ig, ui: { label: "straightlaced", toLabel: "straitlaced", copyLabels: true, mw: "straitlaced" }, type: IssueType.SP },
  sub_par: { regex: /sub-par/ig, ui: { label: "sub-par", toLabel: "subpar", copyLabels: true, mw: "subpar" }, type: IssueType.SP },
  sun_tan: { regex: /sun-tan/ig, ui: { label: "sun-tan", toLabel: "suntan", copyLabels: true, mw: "suntan" }, type: IssueType.SP },
  swiss: { regex: /swiss cheese/g, ui: { label: "swiss cheese", toLabel: "Swiss cheese", copyLabels: true, mw: "Swiss cheese" }, type: IssueType.SP },
  t_shirt: { regex: /t-shirt/g, ui: { label: "t-shirt", toLabel: "T-shirt", copyLabels: true, mw: "T-shirt" }, type: IssueType.SP },
  tastebud: { regex: /tastebud/ig, ui: { label: "tastebud", toLabel: "taste bud", copyLabels: true, mw: "taste bud" }, type: IssueType.SP },
  tax_payer: { regex: /tax-payer/ig, ui: { label: "tax-payer", toLabel: "taxpayer", copyLabels: true, mw: "taxpayer" }, type: IssueType.SP },
  tax_paying: { regex: /tax-paying/ig, ui: { label: "tax-paying", toLabel: "taxpaying", copyLabels: true, mw: "taxpaying" }, type: IssueType.SP },
  tell_tale: { regex: /tell-tale/ig, ui: { label: "tell-tale", toLabel: "telltale", copyLabels: true, mw: "telltale" }, type: IssueType.SP },
  test_drive: { regex: /test drive/ig, ui: { label: "test drive", toLabel: "test-drive", copyLabels: true, mw: "test-drive" }, type: IssueType.SP },
  testdrive: { regex: /testdrive/ig, ui: { label: "testdrive", toLabel: "test-drive", copyLabels: true, mw: "test-drive" }, type: IssueType.SP },
  testrun: { regex: /testrun/ig, ui: { label: "testrun", toLabel: "test run", copyLabels: true, mw: "test run" }, type: IssueType.SP },
  test_run: { regex: /test-run/ig, ui: { label: "test-run", toLabel: "test run", copyLabels: true, mw: "test run" }, type: IssueType.SP },
  tete_a_tete: { regex: /tete-a-tete/ig, ui: { label: "tete-a-tete", toLabel: "tête-à-tête", copyLabels: true, mw: "tête-à-tête" }, type: IssueType.SP },
  thrusted: { regex: /thrusted/ig, ui: { label: "thrusted", toLabel: "thrust (past tense)", copy: "thrusted", paste: "thrust", mw: "thrust" }, type: IssueType.SP },
  timeframe: { regex: /timeframe/ig, ui: { label: "timeframe", toLabel: "time frame", copyLabels: true, mw: "time frame" }, type: IssueType.SP },
  timestamp: { regex: /timestamp/ig, ui: { label: "timestamp", toLabel: "time stamp", copyLabels: true, mw: "time stamp" }, type: IssueType.SP },
  time_worn: { regex: /time-worn/ig, ui: { label: "time-worn", toLabel: "timeworn", copyLabels: true, mw: "timeworn" }, type: IssueType.SP },
  tipoff: { regex: /tipoff/ig, ui: { label: "tipoff", toLabel: "tip-off", copyLabels: true, mw: "tip-off" }, type: IssueType.SP },
  top_secret: { regex: /top-secret/ig, ui: { label: "top-secret", toLabel: "top secret", copyLabels: true, mw: "top secret" }, type: IssueType.SP },
  travelling: { regex: /travelling/ig, ui: { label: "travelling", toLabel: "traveling", copyLabels: true, mw: "travel" }, type: IssueType.SP },
  travelled: { regex: /travelled/ig, ui: { label: "travelled", toLabel: "traveled", copyLabels: true, mw: "travel" }, type: IssueType.SP },
  traveller: { regex: /traveller/ig, ui: { label: "traveller", toLabel: "traveler", copyLabels: true, mw: "traveler" }, type: IssueType.SP },
  tried_and_true: { regex: /tried and true/ig, ui: { label: "tried and true", toLabel: "tried-and-true (adjective?)", copy: "tried and true", paste: "tried-and-true", mw: "tried-and-true" }, type: IssueType.SP },
  twentyfourseven: { regex: /twenty-four-seven/ig, ui: { label: "twenty-four-seven", toLabel: "twenty-four seven", copyLabels: true, mw: "twenty-four seven" }, type: IssueType.SP },
  twin_tail: { regex: /twin tail/ig, ui: { label: "twin tail", toLabel: "pigtail", copyLabels: true }, type: IssueType.SP },
  twin_tail2: { regex: /twin-tail/ig, ui: { label: "twin-tail", toLabel: "pigtail", copyLabels: true }, type: IssueType.SP },
  twintail: { regex: /twintail/ig, ui: { label: "twintail", toLabel: "pigtail", copyLabels: true }, type: IssueType.SP },
  
  // U through Z
  uh_huh: { regex: /\buh huh/ig, ui: { label: "uh huh", toLabel: "uh-huh", copyLabels: true, mw: "uh-huh" }, type: IssueType.SP },
  underaged: { regex: /underaged/ig, ui: { label: "underaged", toLabel: "underage", copyLabels: true, mw: "underage" }, type: IssueType.SP },
  unshakeable: { regex: /unshakeable/ig, ui: { label: "unshakeable", toLabel: "unshakable", copyLabels: true, mw: "unshakable" }, type: IssueType.SP },
  upperhand: { regex: /upperhand/ig, ui: { label: "upperhand", toLabel: "upper hand", copyLabels: true, mw: "upper hand" }, type: IssueType.SP },
  vice_like: { regex: /vice-like/ig, ui: { label: "vice-like", toLabel: "viselike", copyLabels: true, mw: "viselike" }, type: IssueType.SP },
  vicelike: { regex: /vicelike/ig, ui: { label: "vicelike", toLabel: "viselike", copyLabels: true, mw: "viselike" }, type: IssueType.SP },
  vice_versa: { regex: /vice-versa/ig, ui: { label: "vice-versa", toLabel: "vice versa", copyLabels: true, mw: "vice versa" }, type: IssueType.SP },
  videogame: { regex: /videogame/ig, ui: { label: "videogame", toLabel: "video game", copyLabels: true, mw: "video game" }, type: IssueType.SP },
  vocal_chord: { regex: /vocal chord/ig, ui: { label: "vocal chord", toLabel: "vocal cord", copyLabels: true, mw: "vocal cord" }, type: IssueType.SP },
  walkthrough: { regex: /walkthrough/ig, ui: { label: "walkthrough", toLabel: "walk-through", copyLabels: true, mw: "walk-through" }, type: IssueType.SP },
  wash_bowl: { regex: /wash bowl/ig, ui: { label: "wash bowl", toLabel: "washbowl (noun?)", copy: "wash bowl", paste: "washbowl", mw: "washbowl" }, type: IssueType.SP },
  week_long: { regex: /week-long/ig, ui: { label: "week-long", toLabel: "weeklong", copyLabels: true, mw: "weeklong" }, type: IssueType.SP },
  wellbeing: { regex: /wellbeing/ig, ui: { label: "wellbeing", toLabel: "well-being", copyLabels: true, mw: "well-being" }, type: IssueType.SP },
  wellkempt: { regex: /well-kempt/ig, ui: { label: "well-kempt", toLabel: "well-kept", copyLabels: true, mw: "well-kept" }, type: IssueType.SP },
  wide_eyed: { regex: /wide eyed/ig, ui: { label: "wide eyed", toLabel: "wide-eyed", copyLabels: true, mw: "wide-eyed" }, type: IssueType.SP },
  wide_spread: { regex: /wide-spread/ig, ui: { label: "wide-spread", toLabel: "widespread", copyLabels: true, mw: "widespread" }, type: IssueType.SP },
  willy_nilly: { regex: /willy nilly/ig, ui: { label: "willy nilly", toLabel: "willy-nilly", copyLabels: true, mw: "willy-nilly" }, type: IssueType.SP },
  wishlist: { regex: /wishlist/ig, ui: { label: "wishlist", toLabel: "wish list", copyLabels: true, mw: "wish list" }, type: IssueType.SP },
  woah: { regex: /woah/ig, ui: { label: "woah", toLabel: "whoa", copyLabels: true, mw: "whoa" }, type: IssueType.SP },
  worshiping: { regex: /worshiping/ig, ui: { label: "worshiping", toLabel: "worshipping", copyLabels: true, mw: "worship" }, type: IssueType.SP },
  worshiper: { regex: /worshiper/ig, ui: { label: "worshiper", toLabel: "worshipper", copyLabels: true, mw: "worshipper" }, type: IssueType.SP },
  worst_case_scenario: { regex: /worst case scenario/ig, ui: { label: "worst case scenario", toLabel: "worst-case scenario", copyLabels: true, mw: "worst-case" }, type: IssueType.SP },
  yada_yada: { regex: /yada-yada/ig, ui: { label: "yada-yada", toLabel: "yada yada", copyLabels: true, mw: "yada yada" }, type: IssueType.SP },
  year_long: { regex: /year-long/ig, ui: { label: "year-long", toLabel: "yearlong", copyLabels: true, mw: "yearlong" }, type: IssueType.SP },

  // Compare similar words
  afterwards: { regex: /afterwards/ig, ui: { label: "afterwards", copy: "afterwards" }, type: IssueType.SW },
  afterward: { regex: /afterward($|[^s])/ig, ui: { label: "afterward", copy: "afterward[^s]" }, type: IssueType.SW },
  anymore: { regex: /\banymore\b/ig, ui: { label: "anymore", copy: "anymore" }, type: IssueType.SW },
  any_more: { regex: /\bany more\b/ig, ui: { label: "any more", copy: "any more" }, type: IssueType.SW },
  further: { regex: /further/ig, ui: { label: "further", copy: "further" }, type: IssueType.SW },
  farther: { regex: /farther/ig, ui: { label: "farther", copy: "farther" }, type: IssueType.SW },
  leaped: { regex: /leaped/ig, ui: { label: "leaped", copy: "leaped" }, type: IssueType.SW },
  leapt: { regex: /leapt/ig, ui: { label: "leapt", copy: "leapt" }, type: IssueType.SW },
  towards: { regex: /towards/ig, ui: { label: "towards", copy: "towards" }, type: IssueType.SW },
  toward: { regex: /toward($|[^s])/ig, ui: { label: "toward", copy: "toward[^s]" }, type: IssueType.SW },

  // Possible slurs and offensive terms
  spaz: { regex: /\bspaz\b/ig, ui: { label: "spaz (slur?)", copy: "spaz" }, type: IssueType.SL },
  retard: { regex: /retard/ig, ui: { label: "retard (slur?)", copy: "retard" }, type: IssueType.SL },
  fuck: { regex: /fuck/ig, ui: { label: "fuck (curse word)", copy: "fuck" }, type: IssueType.SL },
};

// variable is unused, but forces a type check
const unusedTypeCheck = idlessIssues as { [key: string]: Omit<Issue, "id"> };

type IdlessIssues = { [key in IssueId]: Omit<Issues[key], 'id'> };

function copyObjectIdsToValues(idlessIssues: IdlessIssues): Issues {
  const issues: Partial<Issues> = {};
  for (const key in idlessIssues) {
    const id = key as IssueId;
    issues[id] = { id, ...idlessIssues[id] as Omit<Issue, 'id'> };
  }
  return issues as Issues;
}

export const issues = copyObjectIdsToValues(idlessIssues);
